Xapian Erlang Binding: ParamDecoderController Class Reference
ParamDecoderController Class Reference
#include <param_decoder_controller.h>
Public Member Functions
ParamDecoderController (const char *buf, const size_t len)
ParamDecoderController (const ParamDecoderController &prototype)
~ParamDecoderController ()
operator ParamDecoder () const
Private Member Functions
void init (const char *buf, const size_t len)
Private Attributes
char * m_buf
size_t m_len
Detailed Description
This object is for storing a paramDecoder buffer as a resource
Definition at line 13 of file param_decoder_controller.h.
Constructor & Destructor Documentation
ParamDecoderController::ParamDecoderController (const char * buf, const size_t len)
Constructor
Definition at line 25 of file param_decoder_controller.cpp.
References init().
ParamDecoderController::ParamDecoderController (const ParamDecoderController & prototype)
Definition at line 30 of file param_decoder_controller.cpp.
References init(), m_buf, and m_len.
ParamDecoderController::~ParamDecoderController ()
Definition at line 35 of file param_decoder_controller.cpp.
References m_buf.
Member Function Documentation
XAPIAN_ERLANG_NS_BEGIN void ParamDecoderController::init (const char * buf, const size_t len) private
Definition at line 10 of file param_decoder_controller.cpp.
References m_buf, and m_len.
Referenced by ParamDecoderController().
ParamDecoderController::operator ParamDecoder () const
Definition at line 40 of file param_decoder_controller.cpp.
Member Data Documentation
char* ParamDecoderController::m_buf private
Definition at line 15 of file param_decoder_controller.h.
Referenced by init(), ParamDecoderController(), and ~ParamDecoderController().
size_t ParamDecoderController::m_len private
Definition at line 16 of file param_decoder_controller.h.
Referenced by init(), and ParamDecoderController().
The documentation for this class was generated from the following files:
c_src/param_decoder_controller.h
c_src/param_decoder_controller.cpp