Xapian Erlang Binding: SpellingFreqManipulation Class Reference
SpellingFreqManipulation Class Reference
#include <sf_manipulation.h>
Public Member Functions
SpellingFreqManipulation (Xapian::WritableDatabase &wdb, const std::string &tname)
Xapian::termcount current_frequency ()
void dec_frequency (const Xapian::termcount frequency)
void inc_frequency (const Xapian::termcount frequency)
void set_frequency (const Xapian::termcount frequency)
void clear_frequency ()
Private Attributes
bool m_is_exist
Xapian::WritableDatabase & m_wdb
const std::string & m_tname
Detailed Description
Definition at line 8 of file sf_manipulation.h.
Constructor & Destructor Documentation
SpellingFreqManipulation::SpellingFreqManipulation (Xapian::WritableDatabase & wdb, const std::string & tname) inline
Definition at line 19 of file sf_manipulation.h.
References Helpers::isSpellingExist().
Member Function Documentation
void SpellingFreqManipulation::clear_frequency () inline
Definition at line 57 of file sf_manipulation.h.
References set_frequency().
Referenced by Helpers::tryRemoveSpelling().
Xapian::termcount SpellingFreqManipulation::current_frequency () inline
Definition at line 28 of file sf_manipulation.h.
References Helpers::getSpellingFrequency(), m_tname, and m_wdb.
Referenced by set_frequency().
void SpellingFreqManipulation::dec_frequency (const Xapian::termcount frequency) inline
Definition at line 34 of file sf_manipulation.h.
References m_tname, and m_wdb.
Referenced by set_frequency(), and Helpers::tryDecreaseSpellingFreq().
void SpellingFreqManipulation::inc_frequency (const Xapian::termcount frequency) inline
Definition at line 40 of file sf_manipulation.h.
References m_tname, and m_wdb.
Referenced by set_frequency().
void SpellingFreqManipulation::set_frequency (const Xapian::termcount frequency) inline
Definition at line 46 of file sf_manipulation.h.
References current_frequency(), dec_frequency(), and inc_frequency().
Referenced by clear_frequency(), and Helpers::trySetSpellingFreq().
Member Data Documentation
bool SpellingFreqManipulation::m_is_exist private
The term position, used for manipulation. It can or cannot exist.
Definition at line 14 of file sf_manipulation.h.
const std::string& SpellingFreqManipulation::m_tname private
Definition at line 16 of file sf_manipulation.h.
Referenced by current_frequency(), dec_frequency(), and inc_frequency().
Xapian::WritableDatabase& SpellingFreqManipulation::m_wdb private
Definition at line 15 of file sf_manipulation.h.
Referenced by current_frequency(), dec_frequency(), and inc_frequency().
The documentation for this class was generated from the following file:
c_src/common/sf_manipulation.h