Xapian Erlang Binding: Iterator Class Reference
Iterator Class Reference
Contains functions for iterator creation and retrieving information.
#include <termiter_gen.h>
Public Member Functions
virtual Xapian::TermIterator begin ()=0
virtual Xapian::TermIterator end ()=0
virtual ~Iterator ()
virtual Xapian::termcount size ()
virtual bool empty ()
Static Public Member Functions
static Iterator * create (ParamDecoder &params, Xapian::ValueCountMatchSpy &spy)
static Iterator * create (Xapian::Document &doc)
static Iterator * create (ParamDecoder &params, Xapian::QueryParser &qp)
static Iterator * create (ParamDecoder &params, Xapian::Database &db)
Detailed Description
Contains functions for iterator creation and retrieving information.
It provides an interface for term iteration. Each object contains state with a term set.
Used from Driver::termGenerator for QLC iterators.
Definition at line 27 of file termiter_gen.h.
Constructor & Destructor Documentation
virtual Iterator::~Iterator () inline virtual
Definition at line 32 of file termiter_gen.h.
Member Function Documentation
virtual Xapian::TermIterator Iterator::begin () pure virtual
Implemented in StopList, Synonyms, TopValues, Unstem, Spellings, Terms, and Values.
Referenced by empty().
Iterator * Iterator::create (ParamDecoder & params, Xapian::ValueCountMatchSpy & spy) static
Create from Spy.
Definition at line 27 of file termiter_gen.cpp.
References TOP_VALUES, and VALUES.
Iterator * Iterator::create (Xapian::Document & doc) static
Definition at line 52 of file termiter_gen.cpp.
Iterator * Iterator::create (ParamDecoder & params, Xapian::QueryParser & qp) static
Definition at line 59 of file termiter_gen.cpp.
References STOP_LIST, and UNSTEM.
Iterator * Iterator::create (ParamDecoder & params, Xapian::Database & db) static
Definition at line 83 of file termiter_gen.cpp.
References SPELLINGS, and SYNONYMS.
virtual bool Iterator::empty () inline virtual
Definition at line 42 of file termiter_gen.h.
References begin(), and end().
virtual Xapian::TermIterator Iterator::end () pure virtual
Implemented in StopList, Synonyms, TopValues, Unstem, Spellings, Terms, and Values.
Referenced by empty().
virtual Xapian::termcount Iterator::size () inline virtual
If size() is unknown, return 0. To check size is really 0, use empty().
Reimplemented in Terms.
Definition at line 38 of file termiter_gen.h.
The documentation for this class was generated from the following files:
c_src/common/termiter_gen.h
c_src/common/termiter_gen/termiter_gen.cpp