Xapian Erlang Binding: Factory Class Reference
Factory Class Reference
#include <factory.h>
Public Member Functions
Factory ()
Element extract (ParamDecoder &params)
void skip (ParamDecoder &params)
Element extract (Element &context, ParamDecoder &params)
void save (Element &element, ResultEncoder &result)
Element create (ParamDecoder &params)
void release (ParamDecoder &params)
void multiRelease (ParamDecoder &params)
void getResourceConstructors (ResultEncoder &result)
Private Types
enum ResourceSchemaType { SCHEMA_TYPE_REFERENCE = 56, SCHEMA_TYPE_CONSTRUCTOR = 97, SCHEMA_UNDEFINED = 61 }
Private Attributes
Generator m_generator
Register m_register
Detailed Description
Definition at line 17 of file factory.h.
Member Enumeration Documentation
enum Factory::ResourceSchemaType private
Enumerator:
SCHEMA_TYPE_REFERENCE
SCHEMA_TYPE_CONSTRUCTOR
SCHEMA_UNDEFINED
Definition at line 19 of file factory.h.
Constructor & Destructor Documentation
XAPIAN_RESOURCE_NS_BEGIN Factory::Factory ()
Definition at line 8 of file factory.cpp.
References m_generator, and Generator::registerCallbacks().
Member Function Documentation
Element Factory::create (ParamDecoder & params)
Definition at line 48 of file factory.cpp.
References Generator::create(), m_generator, and m_register.
Element Factory::extract (ParamDecoder & params)
Definition at line 55 of file factory.cpp.
References Generator::create(), Register::get(), m_generator, m_register, SCHEMA_TYPE_CONSTRUCTOR, and SCHEMA_TYPE_REFERENCE.
Referenced by extract().
Element Factory::extract (Element & context, ParamDecoder & params)
Definition at line 39 of file factory.cpp.
References Element::attach(), and extract().
void Factory::getResourceConstructors (ResultEncoder & result)
Get a metadata about constructors. It is called from xapian_server:init/2.
Definition at line 110 of file factory.cpp.
References Generator::constructor_begin(), Generator::constructor_end(), m_generator, and Constructor::name().
void Factory::multiRelease (ParamDecoder & params)
Definition at line 31 of file factory.cpp.
References m_register, and Register::removeAny().
void Factory::release (ParamDecoder & params)
Definition at line 23 of file factory.cpp.
References m_register, and Register::remove().
void Factory::save (Element & element, ResultEncoder & result)
Definition at line 15 of file factory.cpp.
References m_register, and Register::put().
void Factory::skip (ParamDecoder & params)
Definition at line 79 of file factory.cpp.
References Generator::create(), m_generator, m_register, SCHEMA_TYPE_CONSTRUCTOR, SCHEMA_TYPE_REFERENCE, and SCHEMA_UNDEFINED.
Member Data Documentation
Generator Factory::m_generator private
Definition at line 29 of file factory.h.
Referenced by create(), extract(), Factory(), getResourceConstructors(), and skip().
Register Factory::m_register private
Definition at line 30 of file factory.h.
Referenced by create(), extract(), multiRelease(), release(), save(), and skip().
The documentation for this class was generated from the following files:
c_src/common/resource/factory.h
c_src/common/resource/factory.cpp