Xapian Erlang Binding: Driver Class Reference
Driver Class Reference
#include <xapian_core.h>
Public Types
enum e_command {
OPEN = 0, LAST_DOC_ID = 1, ADD_DOCUMENT = 2, TEST = 3,
GET_DOCUMENT_BY_ID = 4, START_TRANSACTION = 5, CANCEL_TRANSACTION = 6, COMMIT_TRANSACTION = 7,
QUERY_PAGE = 8, SET_DEFAULT_STEMMER = 9, SET_DEFAULT_PREFIXES = 10, ENQUIRE = 11,
RELEASE_RESOURCE = 12, MATCH_SET = 13, QLC_INIT = 14, QLC_NEXT_PORTION = 15,
QLC_LOOKUP = 16, GET_RESOURCE_CONSTRUCTORS = 17, CREATE_RESOURCE = 18, MSET_INFO = 19,
DB_INFO = 20, DELETE_DOCUMENT = 21, REPLACE_OR_CREATE_DOCUMENT = 22, SET_METADATA = 23,
UPDATE_DOCUMENT = 24, UPDATE_OR_CREATE_DOCUMENT = 25, DOCUMENT = 26, OPEN_PROG = 27,
OPEN_TCP = 28, CLOSE = 29, DOCUMENT_INFO = 30, DOCUMENT_INFO_RESOURCE = 31,
IS_DOCUMENT_EXIST = 32, REPLACE_DOCUMENT = 33, RELEASE_RESOURCES = 34, MATCH_SPY_INFO = 35,
CREATE_QUERY_PARSER = 36, PARSE_STRING = 37, ADD_SPELLING = 38
}
enum e_errorCode { SUCCESS = 0, ERROR = 1 }
enum e_uniqueIdType { UNIQUE_DOCID = 1, UNIQUE_TERM = 2 }
enum e_openMode {
READ_OPEN = 0, WRITE_CREATE_OR_OPEN = 1, WRITE_CREATE = 2, WRITE_CREATE_OR_OVERWRITE = 3,
WRITE_OPEN = 4
}
enum e_fieldTypeIn {
STEMMER = 1, DATA = 2, DELTA = 3, TEXT = 4,
TERM_GENERATOR = 5, SET_POSTING = 15, ADD_POSTING = 25, UPDATE_POSTING = 35,
REMOVE_POSTING = 45, SET_TERM = 16, ADD_TERM = 26, UPDATE_TERM = 36,
REMOVE_TERM = 46, ADD_VALUE = 17, SET_VALUE = 27, UPDATE_VALUE = 37,
REMOVE_VALUE = 47, DEC_WDF = 101, SET_WDF = 111, REMOVE_VALUES = 103,
REMOVE_TERMS = 104, REMOVE_POSITIONS = 105, REMOVE_TERM_POSITIONS = 106, REMOVE_TERM_POSITIONS_SAVE = 116
}
enum e_fieldTypeOut {
GET_VALUE = 1, GET_FLOAT_VALUE = 2, GET_DATA = 3, GET_DOCID = 4,
GET_WEIGHT = 5, GET_RANK = 6, GET_PERCENT = 7, GET_MULTI_DOCID = 8,
GET_DB_NUMBER = 9
}
enum e_encodedValueType { STRING_TYPE = 0, DOUBLE_TYPE = 1 }
enum e_testNumber { TEST_RESULT_ENCODER = 1, TEST_EXCEPTION = 2, TEST_ECHO = 3, TEST_MEMORY = 4 }
enum e_queryType {
QUERY_GROUP = 1, QUERY_VALUE = 2, QUERY_VALUE_RANGE = 3, QUERY_TERM = 4,
QUERY_PARSER = 5, QUERY_SCALE_WEIGHT = 6, QUERY_REFERENCE = 7
}
enum e_queryParserCommand {
QP_STEMMER = 1, QP_STEMMING_STRATEGY = 2, QP_MAX_WILDCARD_EXPANSION = 3, QP_DEFAULT_OP = 4,
QP_PARSER_TYPE = 5, QP_PREFIX = 6, QP_VALUE_RANGE_PROCESSOR = 7, QP_FROM_RESOURCE = 8,
QP_STEMMER_RESOURCE = 9, QP_STOPPER_RESOURCE = 10
}
enum e_termGeneratorCommand {
TG_STEMMER = 1, TG_STEMMING_STRATEGY = 2, TG_GENERATOR_TYPE = 3, TG_FROM_RESOURCE = 4,
TG_STEMMER_RESOURCE = 5, TG_STOPPER_RESOURCE = 6
}
enum e_queryParserType { QP_TYPE_DEFAULT = 0, QP_TYPE_EMPTY = 1 }
enum e_termGeneratorType { TG_TYPE_DEFAULT = 0, TG_TYPE_EMPTY = 1 }
enum e_parseStringFieldId { PS_QUERY_RESOURCE = 1, PS_CORRECTED_QUERY_STRING = 2 }
enum e_enquireCommand {
EC_STOP = 0, EC_QUERY = 1, EC_QUERY_LEN = 2, EC_ORDER = 3,
EC_DOCID_ORDER = 4, EC_WEIGHTING_SCHEME = 5, EC_CUTOFF = 6, EC_COLLAPSE_KEY = 7
}
see `xapian_enquire:encode'
enum e_enquireOrderTypes {
OT_KEY = 1, OT_VALUE = 2, OT_KEY_RELEVANCE = 3, OT_RELEVANCE_KEY = 4,
OT_RELEVANCE_VALUE = 5, OT_VALUE_RELEVANCE = 6
}
enum e_msetInfoParams {
MI_MATCHES_LOWER_BOUND = 1, MI_MATCHES_ESTIMATED = 2, MI_MATCHES_UPPER_BOUND = 3, MI_UNCOLLAPSED_MATCHES_LOWER_BOUND = 4,
MI_UNCOLLAPSED_MATCHES_ESTIMATED = 5, MI_UNCOLLAPSED_MATCHES_UPPER_BOUND = 6, MI_SIZE = 7, MI_GET_MAX_POSSIBLE = 8,
MI_GET_MAX_ATTAINED = 9, MI_TERM_WEIGHT = 10, MI_TERM_FREQ = 11
}
enum e_matchSpyInfoParams { SI_DOCUMENT_COUNT = 1, SI_VALUE_SLOT = 2 }
enum e_dbInfoParams {
DBI_HAS_POSITIONS = 1, DBI_DOCCOUNT = 2, DBI_LASTDOCID = 3, DBI_AVLENGTH = 4,
DBI_TERM_EXISTS = 5, DBI_TERM_FREQ = 6, DBI_COLLECTION_FREQ = 7, DBI_VALUE_FREQ = 8,
DBI_VALUE_LOWER_BOUND = 9, DBI_VALUE_UPPER_BOUND = 10, DBI_DOCLENGTH_LOWER_BOUND = 11, DBI_DOCLENGTH_UPPER_BOUND = 12,
DBI_WDF_UPPER_BOUND = 13, DBI_DOCLENGTH = 14, DBI_UUID = 15, DBI_METADATA = 16
}
enum e_termInfoFields {
TERM_VALUE = 1, TERM_WDF = 2, TERM_FREQ = 3, TERM_POSITIONS = 4,
TERM_POS_COUNT = 5, TERM_FLOAT_VALUE = 6
}
enum e_decoderTypeFunIds { DEC_DOCUMENT = 0, DEC_ITERATOR = 1, DEC_BOTH = 2 }
enum e_textFlags { TEXT_FLAG_POSITIONS = 1 }
Public Member Functions
ResultEncoder * getResultEncoder ()
Driver (MemoryManager &)
~Driver ()
void handleCommand (PR, const unsigned int command)
void setDefaultStemmer (const Xapian::Stem &stemmer)
int openWriteMode (uint8_t mode)
Xapian::Document getDocument (ParamDecoder &)
void retrieveDocument (PCR, Xapian::Document &, Xapian::MSetIterator &)
void retrieveDocument (PCR, Xapian::Document &)
void retrieveDocument (PCR, Xapian::MSetIterator &)
void retrieveDocuments (PCR, Xapian::MSetIterator, Xapian::MSetIterator)
void selectEncoderAndRetrieveDocument (PR, Xapian::MSetIterator &)
ParamDecoderController retrieveDocumentSchema (ParamDecoder &) const
ParamDecoderController retrieveTermSchema (ParamDecoder &) const
void applyDocument (ParamDecoder &, Xapian::Document &doc)
ParamDecoderController applyDocumentSchema (ParamDecoder &)
Xapian::Query buildQuery (CP)
void fillEnquire (CP, Xapian::Enquire &enquire)
void fillEnquireOrder (CP, Xapian::Enquire &enquire)
void assertWriteable () const
Xapian::QueryParser readParser (CP)
Xapian::QueryParser selectParser (ParamDecoder &)
Xapian::TermGenerator readGenerator (CP)
Xapian::TermGenerator selectGenerator (ParamDecoder &params)
void addPrefix (ParamDecoder &, Xapian::QueryParser &qp)
void addPrefix (ParamDecoder &, QueryParserFactory &qpf)
Command helpers.
void setDefaultStemmer (ParamDecoder &params)
void setDefaultPrefixes (ParamDecoder &params)
void open (uint8_t mode, const std::string &dbpath)
void open (uint8_t mode, const std::string &host, uint16_t port, uint32_t timeout, uint32_t connect_timeout)
void open (uint8_t mode, const std::string &prog, const std::string &args, uint32_t timeout)
void getLastDocId (ResultEncoder &)
void addDocument (PR)
void addSpelling (ParamDecoder &)
void replaceDocument (PR)
void replaceOrCreateDocument (PR)
void updateDocument (PR, bool create)
void isDocumentExist (PR)
void deleteDocument (PR)
void setMetadata (ParamDecoder &)
void query (CPR)
void enquire (PR)
void document (PR)
void valueMatchSpyToSlot (PR)
void releaseResource (ParamDecoder &)
void releaseResources (ParamDecoder &)
void matchSet (CPR)
void qlcInit (PR)
void qlcNext (PR)
void qlcLookup (PR)
void startTransaction ()
void cancelTransaction ()
void commitTransaction ()
void getDocumentById (PR)
void documentInfo (PR)
void documentInfoResource (PR)
void matchSpyInfo (PR)
void testResultEncoder (ResultEncoder &, Xapian::docid from, Xapian::docid to)
void testEcho (PR)
void testException ()
void testMemory ()
void getResourceConstructors (ResultEncoder &)
void createResource (PR)
void test (PR)
void msetInfo (PR)
void databaseInfo (PR)
Static Public Member Functions
static void retrieveTerm (PCR, const Xapian::TermIterator &iter)
static unsigned idToParserFeature (int type)
static unsigned decodeParserFeatureFlags (ParamDecoder &)
static unsigned idToGeneratorFeature (int type)
static unsigned idToTextFeature (int type)
static void decodeGeneratorFeatureFlags (ParamDecoder &params, unsigned &genFlags, unsigned &textFlags)
static
Xapian::QueryParser::stem_strategy readStemmingStrategy (ParamDecoder &)
Static Public Attributes
static const unsigned PARSER_FEATURES []
static const uint8_t PARSER_FEATURE_COUNT = 13
static const unsigned GENERATOR_FEATURES []
static const uint8_t GENERATOR_FEATURE_COUNT = 2
static const int GENERATOR_AND_TEXT_FEATURES_DELIM = 50
Used to separate generator and text features.
static const unsigned GENERATOR_DEFAULT_FEATURES = 0
Default flags.
static const unsigned TEXT_DEFAULT_FEATURES = Driver::TEXT_FLAG_POSITIONS
static const int GENERATOR_AND_TEXT_DEFAULT_FEATURES = 50
Reset settings to default flag.
static const unsigned TEXT_FEATURES []
static const uint8_t TEXT_FEATURE_COUNT = 2
static const uint8_t STEM_STRATEGY_COUNT = 3
static const
Xapian::QueryParser::stem_strategy STEM_STRATEGIES []
static const uint8_t DOCID_ORDER_TYPE_COUNT = 3
static const
Xapian::Enquire::docid_order DOCID_ORDER_TYPES []
Private Member Functions
Driver & operator= (const Driver &)
Driver (const Driver &source)
Xapian::docid docid_sub (const Xapian::docid docid_combined)
Xapian::docid subdb_num (const Xapian::docid docid_combined)
Xapian::Stem & extractStem (CP)
Xapian::Stopper & extractStopper (CP)
Xapian::QueryParser & extractQueryParser (CP)
Xapian::Query & extractQuery (CP)
Xapian::MatchSpy & extractSpy (CP)
Xapian::MatchSpy & extractWritableSpy (CP)
Xapian::ValueRangeProcessor & extractRangeProcessor (CP)
Xapian::Weight & extractWeight (CP)
Xapian::KeyMaker & extractKeyMaker (CP)
Xapian::Enquire & extractEnquire (CP)
Xapian::MSet & extractMSet (CP)
void createQueryParser (PR)
void parseString (CPR)
void setDatabaseAgain ()
Private Attributes
Xapian::Database m_db
Xapian::WritableDatabase m_wdb
Xapian::Stem m_default_stemmer
Xapian::QueryParser m_default_parser
Xapian::QueryParser m_standard_parser
Xapian::TermGenerator m_default_generator
Xapian::TermGenerator m_standard_generator
QueryParserFactory m_default_parser_factory
QueryParserFactory m_standard_parser_factory
TermGeneratorFactory m_default_generator_factory
TermGeneratorFactory m_standard_generator_factory
Resource::Factory m_store
unsigned m_number_of_databases
MemoryManager & m_mm
Friends
class MSetQlcTable
class TermQlcTable
Private static helpers.
TermGenerator::Iterator * termGenerator (ParamDecoder &params, int8_t qlc_type, int8_t resource_type, uint32_t resource_num)
static void handlePosting (ParamDecoder &, uint8_t command, Xapian::Document &doc)
static void handleValue (ParamDecoder &, uint8_t command, Xapian::Document &doc)
static void handleTerm (ParamDecoder &, uint8_t command, Xapian::Document &doc)
static void handleSpelling (ParamDecoder &, uint8_t command, Xapian::WritableDatabase &mdb)
static void qlcTermIteratorLookup (ParamDecoder &driver_params, const ParamDecoder &schema_params, ResultEncoder &result, Xapian::TermIterator iter, const Xapian::TermIterator end)
static const std::string decodeValue (ParamDecoder &params)
Additional Inherited Members
Detailed Description
Definition at line 25 of file xapian_core.h.
Member Enumeration Documentation
enum Driver::e_command
Enumerator:
OPEN
LAST_DOC_ID
ADD_DOCUMENT
TEST
GET_DOCUMENT_BY_ID
START_TRANSACTION
CANCEL_TRANSACTION
COMMIT_TRANSACTION
QUERY_PAGE
SET_DEFAULT_STEMMER
SET_DEFAULT_PREFIXES
ENQUIRE
RELEASE_RESOURCE
MATCH_SET
QLC_INIT
QLC_NEXT_PORTION
QLC_LOOKUP
GET_RESOURCE_CONSTRUCTORS
CREATE_RESOURCE
MSET_INFO
DB_INFO
DELETE_DOCUMENT
REPLACE_OR_CREATE_DOCUMENT
SET_METADATA
UPDATE_DOCUMENT
UPDATE_OR_CREATE_DOCUMENT
DOCUMENT
OPEN_PROG
OPEN_TCP
CLOSE
DOCUMENT_INFO
DOCUMENT_INFO_RESOURCE
IS_DOCUMENT_EXIST
REPLACE_DOCUMENT
RELEASE_RESOURCES
MATCH_SPY_INFO
CREATE_QUERY_PARSER
PARSE_STRING
ADD_SPELLING
Definition at line 68 of file xapian_core.h.
enum Driver::e_dbInfoParams
Enumerator:
DBI_HAS_POSITIONS
DBI_DOCCOUNT
DBI_LASTDOCID
DBI_AVLENGTH
DBI_TERM_EXISTS
DBI_TERM_FREQ
DBI_COLLECTION_FREQ
DBI_VALUE_FREQ
DBI_VALUE_LOWER_BOUND
DBI_VALUE_UPPER_BOUND
DBI_DOCLENGTH_LOWER_BOUND
DBI_DOCLENGTH_UPPER_BOUND
DBI_WDF_UPPER_BOUND
DBI_DOCLENGTH
DBI_UUID
DBI_METADATA
Definition at line 284 of file xapian_core.h.
enum Driver::e_decoderTypeFunIds
Enumerator:
DEC_DOCUMENT
DEC_ITERATOR
DEC_BOTH
Definition at line 312 of file xapian_core.h.
enum Driver::e_encodedValueType
Enumerator:
STRING_TYPE
DOUBLE_TYPE
Definition at line 181 of file xapian_core.h.
enum Driver::e_enquireCommand
see `xapian_enquire:encode'
Enumerator:
EC_STOP
EC_QUERY
EC_QUERY_LEN
EC_ORDER
EC_DOCID_ORDER
EC_WEIGHTING_SCHEME
EC_CUTOFF
EC_COLLAPSE_KEY
Definition at line 244 of file xapian_core.h.
enum Driver::e_enquireOrderTypes
Enumerator:
OT_KEY
OT_VALUE
OT_KEY_RELEVANCE
OT_RELEVANCE_KEY
OT_RELEVANCE_VALUE
OT_VALUE_RELEVANCE
Definition at line 255 of file xapian_core.h.
enum Driver::e_errorCode
Enumerator:
SUCCESS
ERROR
Definition at line 113 of file xapian_core.h.
enum Driver::e_fieldTypeIn
Types of fields. Used in the applyDocument function.
Enumerator:
STEMMER
DATA
Set a stemmer.
DELTA
Set data.
TEXT
Add delta.
TERM_GENERATOR
Set text.
SET_POSTING
Select TermGenerator.
ADD_POSTING
Add posting term.
UPDATE_POSTING
REMOVE_POSTING
SET_TERM
ADD_TERM
UPDATE_TERM
REMOVE_TERM
ADD_VALUE
SET_VALUE
UPDATE_VALUE
REMOVE_VALUE
DEC_WDF
SET_WDF
REMOVE_VALUES
REMOVE_TERMS
Clear all values.
REMOVE_POSITIONS
Clear all terms and postings.
REMOVE_TERM_POSITIONS
REMOVE_TERM_POSITIONS_SAVE
Definition at line 136 of file xapian_core.h.
enum Driver::e_fieldTypeOut
Types of the fields. Used in the retrieveDocument function.
Enumerator:
GET_VALUE
GET_FLOAT_VALUE
GET_DATA
GET_DOCID
GET_WEIGHT
GET_RANK
GET_PERCENT
GET_MULTI_DOCID
GET_DB_NUMBER
Definition at line 169 of file xapian_core.h.
enum Driver::e_matchSpyInfoParams
Enumerator:
SI_DOCUMENT_COUNT
SI_VALUE_SLOT
Definition at line 278 of file xapian_core.h.
enum Driver::e_msetInfoParams
Enumerator:
MI_MATCHES_LOWER_BOUND
MI_MATCHES_ESTIMATED
MI_MATCHES_UPPER_BOUND
MI_UNCOLLAPSED_MATCHES_LOWER_BOUND
MI_UNCOLLAPSED_MATCHES_ESTIMATED
MI_UNCOLLAPSED_MATCHES_UPPER_BOUND
MI_SIZE
MI_GET_MAX_POSSIBLE
MI_GET_MAX_ATTAINED
MI_TERM_WEIGHT
MI_TERM_FREQ
Definition at line 264 of file xapian_core.h.
enum Driver::e_openMode
Enumerator:
READ_OPEN
WRITE_CREATE_OR_OPEN
WRITE_CREATE
WRITE_CREATE_OR_OVERWRITE
WRITE_OPEN
Definition at line 126 of file xapian_core.h.
enum Driver::e_parseStringFieldId
Enumerator:
PS_QUERY_RESOURCE
PS_CORRECTED_QUERY_STRING
Definition at line 237 of file xapian_core.h.
enum Driver::e_queryParserCommand
Enumerator:
QP_STEMMER
QP_STEMMING_STRATEGY
QP_MAX_WILDCARD_EXPANSION
QP_DEFAULT_OP
QP_PARSER_TYPE
QP_PREFIX
QP_VALUE_RANGE_PROCESSOR
QP_FROM_RESOURCE
QP_STEMMER_RESOURCE
QP_STOPPER_RESOURCE
Definition at line 205 of file xapian_core.h.
enum Driver::e_queryParserType
Enumerator:
QP_TYPE_DEFAULT
QP_TYPE_EMPTY
Definition at line 227 of file xapian_core.h.
enum Driver::e_queryType
Enumerator:
QUERY_GROUP
QUERY_VALUE
QUERY_VALUE_RANGE
QUERY_TERM
QUERY_PARSER
QUERY_SCALE_WEIGHT
QUERY_REFERENCE
query, double
Definition at line 195 of file xapian_core.h.
enum Driver::e_termGeneratorCommand
Enumerator:
TG_STEMMER
TG_STEMMING_STRATEGY
TG_GENERATOR_TYPE
TG_FROM_RESOURCE
TG_STEMMER_RESOURCE
TG_STOPPER_RESOURCE
Definition at line 218 of file xapian_core.h.
enum Driver::e_termGeneratorType
Enumerator:
TG_TYPE_DEFAULT
TG_TYPE_EMPTY
Definition at line 232 of file xapian_core.h.
enum Driver::e_termInfoFields
Enumerator:
TERM_VALUE
TERM_WDF
TERM_FREQ
TERM_POSITIONS
TERM_POS_COUNT
TERM_FLOAT_VALUE
Definition at line 303 of file xapian_core.h.
enum Driver::e_testNumber
Numbers of tests. Used in the test function.
Enumerator:
TEST_RESULT_ENCODER
TEST_EXCEPTION
TEST_ECHO
TEST_MEMORY
Definition at line 188 of file xapian_core.h.
enum Driver::e_textFlags
Enumerator:
TEXT_FLAG_POSITIONS
Definition at line 318 of file xapian_core.h.
enum Driver::e_uniqueIdType
Enumerator:
UNIQUE_DOCID
UNIQUE_TERM
Definition at line 119 of file xapian_core.h.
Constructor & Destructor Documentation
Driver::Driver (const Driver & source) inline private
Copy constructor. Copy is not allowed.
Definition at line 60 of file xapian_core.h.
Driver::Driver (MemoryManager & mm)
A constructor.
Definition at line 98 of file xapian_core.cpp.
Driver::~Driver ()
Definition at line 104 of file xapian_core.cpp.
Member Function Documentation
void Driver::addDocument (PR)
Definition at line 151 of file xapian_core.cpp.
References applyDocument(), assertWriteable(), and m_wdb.
Referenced by handleCommand().
void Driver::addPrefix (ParamDecoder & params, Xapian::QueryParser & qp)
Definition at line 1166 of file xapian_core.cpp.
Referenced by readParser(), and setDefaultPrefixes().
void Driver::addPrefix (ParamDecoder & params, QueryParserFactory & qpf)
Definition at line 1181 of file xapian_core.cpp.
References QueryParserFactory::add_boolean_prefix(), and QueryParserFactory::add_prefix().
void Driver::addSpelling (ParamDecoder & params)
Definition at line 163 of file xapian_core.cpp.
References ADD_TERM, assertWriteable(), DEC_WDF, decodeGeneratorFeatureFlags(), handleSpelling(), m_default_generator, m_wdb, readGenerator(), REMOVE_TERM, SET_TERM, SET_WDF, STEMMER, TERM_GENERATOR, TEXT, TEXT_FLAG_POSITIONS, Helpers::tryDecreaseSpellingFreq(), Helpers::trySetSpellingFreq(), and UPDATE_TERM.
Referenced by handleCommand().
void Driver::applyDocument (ParamDecoder & params, Xapian::Document & doc)
Read commands, encoded by `xapian_document:encode'. Used in update, replace, add document functions.
Definition at line 1969 of file xapian_core.cpp.
References ADD_POSTING, ADD_TERM, ADD_VALUE, Helpers::clearTermPositions(), DATA, DEC_WDF, decodeGeneratorFeatureFlags(), DELTA, handlePosting(), handleTerm(), handleValue(), m_default_generator, readGenerator(), REMOVE_POSITIONS, REMOVE_POSTING, REMOVE_TERM, REMOVE_TERM_POSITIONS, REMOVE_TERMS, REMOVE_VALUE, REMOVE_VALUES, SET_POSTING, SET_TERM, SET_VALUE, SET_WDF, STEMMER, TERM_GENERATOR, TEXT, TEXT_FLAG_POSITIONS, Helpers::tryClearTermPositions(), Helpers::tryDecreaseWDF(), Helpers::trySetWDF(), UPDATE_POSTING, UPDATE_TERM, and UPDATE_VALUE.
Referenced by addDocument(), documentInfo(), documentInfoResource(), replaceDocument(), replaceOrCreateDocument(), and updateDocument().
ParamDecoderController Driver::applyDocumentSchema (ParamDecoder & params)
Run applyDocument without creating the real doc. It is useful, if you want to find the position of the ParamDecoder after running the applyDocument.
Definition at line 2645 of file xapian_core.cpp.
References ADD_POSTING, ADD_TERM, ADD_VALUE, ParamDecoder::currentPosition(), DATA, DEC_WDF, DELTA, m_mm, readGenerator(), REMOVE_POSITIONS, REMOVE_POSTING, REMOVE_TERM, REMOVE_TERM_POSITIONS, REMOVE_TERMS, REMOVE_VALUE, REMOVE_VALUES, SET_POSTING, SET_TERM, SET_VALUE, SET_WDF, STEMMER, TERM_GENERATOR, TEXT, UPDATE_POSTING, UPDATE_TERM, and UPDATE_VALUE.
Referenced by updateDocument().
void Driver::assertWriteable () const
Throws error if the database was opened only for reading.
Definition at line 925 of file xapian_core.cpp.
Referenced by addDocument(), addSpelling(), cancelTransaction(), commitTransaction(), deleteDocument(), replaceDocument(), replaceOrCreateDocument(), setMetadata(), startTransaction(), and updateDocument().
Xapian::Query Driver::buildQuery (CP)
Definition at line 1196 of file xapian_core.cpp.
References decodeParserFeatureFlags(), decodeValue(), extractQuery(), QUERY_GROUP, QUERY_PARSER, QUERY_REFERENCE, QUERY_SCALE_WEIGHT, QUERY_TERM, QUERY_VALUE, QUERY_VALUE_RANGE, and readParser().
Referenced by fillEnquire(), and query().
void Driver::cancelTransaction ()
Definition at line 939 of file xapian_core.cpp.
References assertWriteable(), and m_wdb.
Referenced by handleCommand().
void Driver::commitTransaction ()
Definition at line 948 of file xapian_core.cpp.
References assertWriteable(), and m_wdb.
Referenced by handleCommand().
void Driver::createQueryParser (PR) private
Create a parser with a corrected string inside.
Definition at line 590 of file xapian_core.cpp.
References m_store, and readParser().
Referenced by handleCommand().
void Driver::createResource (PR)
Create a resource object using an user function.
Definition at line 2796 of file xapian_core.cpp.
References m_store.
Referenced by handleCommand().
void Driver::databaseInfo (PR)
Definition at line 2871 of file xapian_core.cpp.
References DBI_AVLENGTH, DBI_COLLECTION_FREQ, DBI_DOCCOUNT, DBI_DOCLENGTH, DBI_DOCLENGTH_LOWER_BOUND, DBI_DOCLENGTH_UPPER_BOUND, DBI_HAS_POSITIONS, DBI_LASTDOCID, DBI_METADATA, DBI_TERM_EXISTS, DBI_TERM_FREQ, DBI_UUID, DBI_VALUE_FREQ, DBI_VALUE_LOWER_BOUND, DBI_VALUE_UPPER_BOUND, DBI_WDF_UPPER_BOUND, and m_db.
Referenced by handleCommand().
void Driver::decodeGeneratorFeatureFlags (ParamDecoder & params, unsigned & genFlags, unsigned & textFlags) static
Reset settings to default flag
Definition at line 1109 of file xapian_core.cpp.
References GENERATOR_AND_TEXT_DEFAULT_FEATURES, GENERATOR_AND_TEXT_FEATURES_DELIM, GENERATOR_DEFAULT_FEATURES, idToGeneratorFeature(), idToTextFeature(), and TEXT_DEFAULT_FEATURES.
Referenced by addSpelling(), and applyDocument().
unsigned Driver::decodeParserFeatureFlags (ParamDecoder & params) static
Definition at line 1071 of file xapian_core.cpp.
References idToParserFeature().
Referenced by buildQuery(), and parseString().
const std::string Driver::decodeValue (ParamDecoder & params) static private
Definition at line 2203 of file xapian_core.cpp.
References DOUBLE_TYPE, and STRING_TYPE.
Referenced by buildQuery(), and handleValue().
void Driver::deleteDocument (PR)
Definition at line 400 of file xapian_core.cpp.
References assertWriteable(), m_db, m_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by handleCommand().
Xapian::docid Driver::docid_sub (const Xapian::docid docid_combined) inline private
Definition at line 569 of file xapian_core.h.
References m_number_of_databases.
Referenced by MSetQlcTable::lookup(), and retrieveDocument().
void Driver::document (PR)
Write a resource.
Definition at line 695 of file xapian_core.cpp.
References getDocument(), and m_store.
Referenced by handleCommand().
void Driver::documentInfo (PR)
Get document metadata without putting it in DB.
Definition at line 969 of file xapian_core.cpp.
References applyDocument(), and retrieveDocument().
Referenced by handleCommand().
void Driver::documentInfoResource (PR)
Return the document resource without putting it in DB.
Definition at line 981 of file xapian_core.cpp.
References applyDocument(), and m_store.
Referenced by handleCommand().
void Driver::enquire (PR)
Write a resource.
Definition at line 570 of file xapian_core.cpp.
References fillEnquire(), m_db, and m_store.
Referenced by getDocument(), handleCommand(), matchSet(), query(), and updateDocument().
Xapian::Enquire& Driver::extractEnquire (CP) inline private
Definition at line 669 of file xapian_core.h.
References m_store.
Referenced by matchSet().
Xapian::KeyMaker& Driver::extractKeyMaker (CP) inline private
Definition at line 663 of file xapian_core.h.
References m_store.
Referenced by fillEnquireOrder().
Xapian::MSet& Driver::extractMSet (CP) inline private
Definition at line 675 of file xapian_core.h.
References m_store.
Xapian::Query& Driver::extractQuery (CP) inline private
Definition at line 636 of file xapian_core.h.
References m_store.
Referenced by buildQuery().
Xapian::QueryParser& Driver::extractQueryParser (CP) inline private
Definition at line 630 of file xapian_core.h.
References m_store.
Xapian::ValueRangeProcessor& Driver::extractRangeProcessor (CP) inline private
Definition at line 651 of file xapian_core.h.
References m_store.
Referenced by readParser().
Xapian::MatchSpy& Driver::extractSpy (CP) inline private
Definition at line 642 of file xapian_core.h.
References m_store.
Xapian::Stem& Driver::extractStem (CP) inline private
Definition at line 618 of file xapian_core.h.
References m_store.
Referenced by readGenerator(), and readParser().
Xapian::Stopper& Driver::extractStopper (CP) inline private
Definition at line 624 of file xapian_core.h.
References m_store.
Referenced by readGenerator(), and readParser().
Xapian::Weight& Driver::extractWeight (CP) inline private
Definition at line 657 of file xapian_core.h.
References m_store.
Referenced by fillEnquire().
Xapian::MatchSpy & Driver::extractWritableSpy (CP) private
Definition at line 756 of file xapian_core.cpp.
References m_store.
Referenced by matchSet().
void Driver::fillEnquire (CP , Xapian::Enquire & enquire)
Definition at line 1299 of file xapian_core.cpp.
References buildQuery(), DOCID_ORDER_TYPE_COUNT, DOCID_ORDER_TYPES, EC_COLLAPSE_KEY, EC_CUTOFF, EC_DOCID_ORDER, EC_ORDER, EC_QUERY, EC_QUERY_LEN, EC_WEIGHTING_SCHEME, extractWeight(), fillEnquireOrder(), and query().
Referenced by enquire().
void Driver::fillEnquireOrder (CP , Xapian::Enquire & enquire)
Definition at line 1369 of file xapian_core.cpp.
References extractKeyMaker(), OT_KEY, OT_KEY_RELEVANCE, OT_RELEVANCE_KEY, OT_RELEVANCE_VALUE, OT_VALUE, and OT_VALUE_RELEVANCE.
Referenced by fillEnquire().
Xapian::Document Driver::getDocument (ParamDecoder & params)
Definition at line 653 of file xapian_core.cpp.
References enquire(), m_db, m_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by document().
void Driver::getDocumentById (PR)
Definition at line 957 of file xapian_core.cpp.
References m_db, and retrieveDocument().
Referenced by handleCommand().
void Driver::getLastDocId (ResultEncoder & result)
Definition at line 141 of file xapian_core.cpp.
References m_db.
Referenced by handleCommand().
void Driver::getResourceConstructors (ResultEncoder & result)
This function will be called inside xapian_open:init
Definition at line 2789 of file xapian_core.cpp.
References m_store.
Referenced by handleCommand().
ResultEncoder* Driver::getResultEncoder ()
void Driver::handleCommand (PR , const unsigned int command)
Read and execute one command from a client.
Definition at line 1637 of file xapian_core.cpp.
References ADD_DOCUMENT, ADD_SPELLING, addDocument(), addSpelling(), CANCEL_TRANSACTION, cancelTransaction(), CLOSE, COMMIT_TRANSACTION, commitTransaction(), CREATE_QUERY_PARSER, CREATE_RESOURCE, createQueryParser(), createResource(), databaseInfo(), DB_INFO, DELETE_DOCUMENT, deleteDocument(), DOCUMENT, document(), DOCUMENT_INFO, DOCUMENT_INFO_RESOURCE, documentInfo(), documentInfoResource(), ENQUIRE, enquire(), ERROR, GET_DOCUMENT_BY_ID, GET_RESOURCE_CONSTRUCTORS, DriverRuntimeError::get_type(), getDocumentById(), getLastDocId(), getResourceConstructors(), IS_DOCUMENT_EXIST, isDocumentExist(), LAST_DOC_ID, m_db, m_wdb, MATCH_SET, MATCH_SPY_INFO, matchSet(), matchSpyInfo(), MSET_INFO, msetInfo(), OPEN, open(), OPEN_PROG, OPEN_TCP, PARSE_STRING, parseString(), QLC_INIT, QLC_LOOKUP, QLC_NEXT_PORTION, qlcInit(), qlcLookup(), qlcNext(), query(), QUERY_PAGE, RELEASE_RESOURCE, RELEASE_RESOURCES, releaseResource(), releaseResources(), REPLACE_DOCUMENT, REPLACE_OR_CREATE_DOCUMENT, replaceDocument(), replaceOrCreateDocument(), SET_DEFAULT_PREFIXES, SET_DEFAULT_STEMMER, SET_METADATA, setDefaultPrefixes(), setDefaultStemmer(), setMetadata(), START_TRANSACTION, startTransaction(), SUCCESS, TEST, test(), UPDATE_DOCUMENT, UPDATE_OR_CREATE_DOCUMENT, and updateDocument().
Referenced by DriverController::control(), and run().
void Driver::handlePosting (ParamDecoder & params, uint8_t command, Xapian::Document & doc) static private
Definition at line 2266 of file xapian_core.cpp.
References ADD_POSTING, Helpers::isPostingExist(), REMOVE_POSTING, Helpers::tryRemovePosting(), and UPDATE_POSTING.
Referenced by applyDocument().
void Driver::handleSpelling (ParamDecoder & params, uint8_t command, Xapian::WritableDatabase & mdb) static private
Definition at line 2155 of file xapian_core.cpp.
References ADD_TERM, Helpers::getSpellingFrequency(), Helpers::isSpellingExist(), REMOVE_TERM, Helpers::tryRemoveSpelling(), and UPDATE_TERM.
Referenced by addSpelling().
void Driver::handleTerm (ParamDecoder & params, uint8_t command, Xapian::Document & doc) static private
Definition at line 2106 of file xapian_core.cpp.
References ADD_TERM, Helpers::getTermFrequency(), Helpers::isTermExist(), REMOVE_TERM, Helpers::tryRemoveTerm(), and UPDATE_TERM.
Referenced by applyDocument().
void Driver::handleValue (ParamDecoder & params, uint8_t command, Xapian::Document & doc) static private
Definition at line 2219 of file xapian_core.cpp.
References ADD_VALUE, decodeValue(), Helpers::isValueExist(), REMOVE_VALUE, Helpers::tryRemoveValue(), and UPDATE_VALUE.
Referenced by applyDocument().
unsigned Driver::idToGeneratorFeature (int type) static
Definition at line 1088 of file xapian_core.cpp.
References GENERATOR_FEATURE_COUNT, and GENERATOR_FEATURES.
Referenced by decodeGeneratorFeatureFlags().
unsigned Driver::idToParserFeature (int type) static
Definition at line 1062 of file xapian_core.cpp.
References PARSER_FEATURE_COUNT, and PARSER_FEATURES.
Referenced by decodeParserFeatureFlags().
unsigned Driver::idToTextFeature (int type) static
Definition at line 1096 of file xapian_core.cpp.
References GENERATOR_AND_TEXT_FEATURES_DELIM, TEXT_FEATURE_COUNT, and TEXT_FEATURES.
Referenced by decodeGeneratorFeatureFlags().
void Driver::isDocumentExist (PR)
Definition at line 439 of file xapian_core.cpp.
References m_db, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by handleCommand().
void Driver::matchSet (CPR)
Converts an enquire into a match set. Write a resource.
Definition at line 718 of file xapian_core.cpp.
References enquire(), extractEnquire(), extractWritableSpy(), m_db, and m_store.
Referenced by handleCommand().
void Driver::matchSpyInfo (PR)
Definition at line 2987 of file xapian_core.cpp.
References m_store, SI_DOCUMENT_COUNT, and SI_VALUE_SLOT.
Referenced by handleCommand().
void Driver::msetInfo (PR)
Definition at line 2804 of file xapian_core.cpp.
References m_store, MI_GET_MAX_ATTAINED, MI_GET_MAX_POSSIBLE, MI_MATCHES_ESTIMATED, MI_MATCHES_LOWER_BOUND, MI_MATCHES_UPPER_BOUND, MI_SIZE, MI_TERM_FREQ, MI_TERM_WEIGHT, MI_UNCOLLAPSED_MATCHES_ESTIMATED, MI_UNCOLLAPSED_MATCHES_LOWER_BOUND, and MI_UNCOLLAPSED_MATCHES_UPPER_BOUND.
Referenced by handleCommand().
void Driver::open (uint8_t mode, const std::string & dbpath)
Definition at line 1854 of file xapian_core.cpp.
References m_db, m_number_of_databases, m_wdb, openWriteMode(), READ_OPEN, setDatabaseAgain(), WRITE_CREATE, WRITE_CREATE_OR_OPEN, WRITE_CREATE_OR_OVERWRITE, and WRITE_OPEN.
Referenced by handleCommand().
void Driver::open (uint8_t mode, const std::string & host, uint16_t port, uint32_t timeout, uint32_t connect_timeout)
Open an remote TCP database.
http://xapian.org/docs/apidoc/html/namespaceXapian_1_1Remote.html
Definition at line 1912 of file xapian_core.cpp.
References m_db, m_number_of_databases, m_wdb, READ_OPEN, setDatabaseAgain(), and WRITE_OPEN.
void Driver::open (uint8_t mode, const std::string & prog, const std::string & args, uint32_t timeout)
Open an remote program database.
http://xapian.org/docs/apidoc/html/namespaceXapian_1_1Remote.html
Definition at line 1945 of file xapian_core.cpp.
References m_db, m_number_of_databases, m_wdb, READ_OPEN, setDatabaseAgain(), and WRITE_OPEN.
int Driver::openWriteMode (uint8_t mode)
Definition at line 1880 of file xapian_core.cpp.
References WRITE_CREATE, WRITE_CREATE_OR_OPEN, WRITE_CREATE_OR_OVERWRITE, and WRITE_OPEN.
Referenced by open().
Driver& Driver::operator= (const Driver &) inline private
Assignment operator. Assignment is not allowed.
Definition at line 56 of file xapian_core.h.
void Driver::parseString (CPR) private
Definition at line 611 of file xapian_core.cpp.
References decodeParserFeatureFlags(), m_store, PS_CORRECTED_QUERY_STRING, PS_QUERY_RESOURCE, and readParser().
Referenced by handleCommand().
void Driver::qlcInit (PR)
Definition at line 766 of file xapian_core.cpp.
References QlcType::DATABASE_TERMS, m_db, m_store, QlcType::MSET, MSetQlcTable, QlcType::QUERY_PARSER_TERMS, retrieveDocumentSchema(), retrieveTermSchema(), MSetQlcTable::size(), TermQlcTable::size(), QlcType::SPY_TERMS, TermQlcTable, and QlcType::TERMS.
Referenced by handleCommand().
void Driver::qlcLookup (PR)
Definition at line 917 of file xapian_core.cpp.
References QlcTable::lookup(), and m_store.
Referenced by handleCommand().
void Driver::qlcNext (PR)
Definition at line 907 of file xapian_core.cpp.
References QlcTable::getPage(), and m_store.
Referenced by handleCommand().
void Driver::qlcTermIteratorLookup (ParamDecoder & driver_params, const ParamDecoder & schema_params, ResultEncoder & result, Xapian::TermIterator iter, const Xapian::TermIterator end) static private
Allow to find and write terms by name.
Helper for TermQlcTable class. Use set order of elements.
Parameters:
driver_params Contains which keys (term names) to find. Ends with "".
schema_params Contains which fields to write.
result A buffer for writing.
iter First term for searching in.
end Last term for searching in.
Definition at line 3045 of file xapian_core.cpp.
References retrieveTerm(), TERM_FLOAT_VALUE, and TERM_VALUE.
Referenced by TermQlcTable::lookup().
void Driver::query (CPR)
`query_page'
Definition at line 475 of file xapian_core.cpp.
References buildQuery(), enquire(), m_db, and retrieveDocuments().
Referenced by fillEnquire(), and handleCommand().
Xapian::TermGenerator Driver::readGenerator (CP)
Definition at line 1563 of file xapian_core.cpp.
References extractStem(), extractStopper(), m_default_generator, m_default_generator_factory, selectGenerator(), TG_FROM_RESOURCE, TG_GENERATOR_TYPE, TG_STEMMER, TG_STEMMER_RESOURCE, TG_STEMMING_STRATEGY, and TG_STOPPER_RESOURCE.
Referenced by addSpelling(), applyDocument(), and applyDocumentSchema().
Xapian::QueryParser Driver::readParser (CP)
Return a cloned parser.
Definition at line 1465 of file xapian_core.cpp.
References addPrefix(), extractRangeProcessor(), extractStem(), extractStopper(), m_default_parser, m_default_parser_factory, m_store, QP_DEFAULT_OP, QP_FROM_RESOURCE, QP_MAX_WILDCARD_EXPANSION, QP_PARSER_TYPE, QP_PREFIX, QP_STEMMER, QP_STEMMER_RESOURCE, QP_STEMMING_STRATEGY, QP_STOPPER_RESOURCE, QP_VALUE_RANGE_PROCESSOR, readStemmingStrategy(), and selectParser().
Referenced by buildQuery(), createQueryParser(), and parseString().
Xapian::QueryParser::stem_strategy Driver::readStemmingStrategy (ParamDecoder & params) static
Definition at line 1144 of file xapian_core.cpp.
References STEM_STRATEGIES, and STEM_STRATEGY_COUNT.
Referenced by readParser().
void Driver::releaseResource (ParamDecoder & params)
Erase the stored object.
Definition at line 705 of file xapian_core.cpp.
References m_store.
Referenced by handleCommand().
void Driver::releaseResources (ParamDecoder & params)
Definition at line 711 of file xapian_core.cpp.
References m_store.
Referenced by handleCommand().
void Driver::replaceDocument (PR)
Definition at line 281 of file xapian_core.cpp.
References applyDocument(), assertWriteable(), m_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by handleCommand().
void Driver::replaceOrCreateDocument (PR)
Definition at line 247 of file xapian_core.cpp.
References applyDocument(), assertWriteable(), m_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by handleCommand().
void Driver::retrieveDocument (PCR , Xapian::Document & doc, Xapian::MSetIterator & mset_iter)
Gets a copy of params.
`params' is a clone.
Definition at line 2426 of file xapian_core.cpp.
References DEC_BOTH, DOUBLE_TYPE, GET_DATA, GET_DB_NUMBER, GET_DOCID, GET_FLOAT_VALUE, GET_MULTI_DOCID, GET_PERCENT, GET_RANK, GET_VALUE, GET_WEIGHT, STRING_TYPE, and subdb_num().
Referenced by documentInfo(), getDocumentById(), retrieveDocuments(), and selectEncoderAndRetrieveDocument().
void Driver::retrieveDocument (PCR , Xapian::Document & doc)
Definition at line 2311 of file xapian_core.cpp.
References DEC_DOCUMENT, DOUBLE_TYPE, GET_DATA, GET_DOCID, GET_FLOAT_VALUE, GET_VALUE, and STRING_TYPE.
void Driver::retrieveDocument (PCR , Xapian::MSetIterator & mset_iter)
Definition at line 2365 of file xapian_core.cpp.
References DEC_ITERATOR, docid_sub(), GET_DB_NUMBER, GET_DOCID, GET_MULTI_DOCID, GET_PERCENT, GET_RANK, GET_WEIGHT, and subdb_num().
void Driver::retrieveDocuments (PCR , Xapian::MSetIterator iter, Xapian::MSetIterator end)
Definition at line 497 of file xapian_core.cpp.
References DEC_BOTH, DEC_DOCUMENT, DEC_ITERATOR, and retrieveDocument().
Referenced by MSetQlcTable::getPage(), and query().
ParamDecoderController Driver::retrieveDocumentSchema (ParamDecoder & params) const
Definition at line 2601 of file xapian_core.cpp.
References ParamDecoder::currentPosition(), GET_DATA, GET_DB_NUMBER, GET_DOCID, GET_FLOAT_VALUE, GET_MULTI_DOCID, GET_PERCENT, GET_RANK, GET_VALUE, GET_WEIGHT, and m_mm.
Referenced by qlcInit().
void Driver::retrieveTerm (PCR , const Xapian::TermIterator & iter) static
params is copy.
Definition at line 2520 of file xapian_core.cpp.
References TERM_FLOAT_VALUE, TERM_FREQ, TERM_POS_COUNT, TERM_POSITIONS, TERM_VALUE, and TERM_WDF.
Referenced by TermQlcTable::getPageKnownSize(), TermQlcTable::getPageUnknownSize(), and qlcTermIteratorLookup().
ParamDecoderController Driver::retrieveTermSchema (ParamDecoder & params) const
Definition at line 2581 of file xapian_core.cpp.
References ParamDecoder::currentPosition(), and m_mm.
Referenced by qlcInit().
void Driver::selectEncoderAndRetrieveDocument (PR , Xapian::MSetIterator & iter)
Read sources of information and write information fields. Sources are selected from Erlang code.
Definition at line 535 of file xapian_core.cpp.
References DEC_BOTH, DEC_DOCUMENT, DEC_ITERATOR, and retrieveDocument().
Referenced by MSetQlcTable::lookup().
Xapian::TermGenerator Driver::selectGenerator (ParamDecoder & params)
Definition at line 1445 of file xapian_core.cpp.
References m_default_generator_factory, m_standard_generator_factory, TG_TYPE_DEFAULT, and TG_TYPE_EMPTY.
Referenced by readGenerator().
Xapian::QueryParser Driver::selectParser (ParamDecoder & params)
Returns a cloned parser.
Definition at line 1428 of file xapian_core.cpp.
References m_default_parser_factory, m_standard_parser_factory, QP_TYPE_DEFAULT, and QP_TYPE_EMPTY.
Referenced by readParser().
void Driver::setDatabaseAgain () private
Definition at line 1841 of file xapian_core.cpp.
References m_db, m_default_generator, m_default_generator_factory, m_default_parser, m_default_parser_factory, m_standard_generator, m_standard_generator_factory, m_standard_parser, m_standard_parser_factory, m_wdb, TermGeneratorFactory::set_database(), and QueryParserFactory::set_database().
Referenced by open().
void Driver::setDefaultPrefixes (ParamDecoder & params)
Definition at line 128 of file xapian_core.cpp.
References addPrefix(), m_default_parser, and m_default_parser_factory.
Referenced by handleCommand().
void Driver::setDefaultStemmer (const Xapian::Stem & stemmer)
Definition at line 109 of file xapian_core.cpp.
References m_default_generator, m_default_generator_factory, m_default_parser, m_default_parser_factory, m_default_stemmer, TermGeneratorFactory::set_stemmer(), and QueryParserFactory::set_stemmer().
Referenced by handleCommand(), and setDefaultStemmer().
void Driver::setDefaultStemmer (ParamDecoder & params)
Definition at line 120 of file xapian_core.cpp.
References setDefaultStemmer().
void Driver::setMetadata (ParamDecoder & params)
Definition at line 3022 of file xapian_core.cpp.
References assertWriteable(), and m_wdb.
Referenced by handleCommand().
void Driver::startTransaction ()
Definition at line 930 of file xapian_core.cpp.
References assertWriteable(), and m_wdb.
Referenced by handleCommand().
Xapian::docid Driver::subdb_num (const Xapian::docid docid_combined) inline private
Definition at line 574 of file xapian_core.h.
References m_number_of_databases.
Referenced by retrieveDocument().
TermGenerator::Iterator* Driver::termGenerator (ParamDecoder & params, int8_t qlc_type, int8_t resource_type, uint32_t resource_num) private
void Driver::test (PR)
Definition at line 992 of file xapian_core.cpp.
References TEST_ECHO, TEST_EXCEPTION, TEST_MEMORY, TEST_RESULT_ENCODER, testEcho(), testException(), testMemory(), and testResultEncoder().
Referenced by handleCommand().
void Driver::testEcho (PR)
Definition at line 1033 of file xapian_core.cpp.
Referenced by test().
void Driver::testException ()
Definition at line 1044 of file xapian_core.cpp.
Referenced by test().
void Driver::testMemory ()
Definition at line 1051 of file xapian_core.cpp.
References MemoryManager::alloc(), MemoryManager::free(), and m_mm.
Referenced by test().
void Driver::testResultEncoder (ResultEncoder & result, Xapian::docid from, Xapian::docid to)
Definition at line 1025 of file xapian_core.cpp.
Referenced by test().
void Driver::updateDocument (PR , bool create)
Definition at line 323 of file xapian_core.cpp.
References applyDocument(), applyDocumentSchema(), assertWriteable(), enquire(), m_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by handleCommand().
void Driver::valueMatchSpyToSlot (PR)
Friends And Related Function Documentation
friend class MSetQlcTable friend
Definition at line 63 of file xapian_core.h.
Referenced by qlcInit().
friend class TermQlcTable friend
Definition at line 64 of file xapian_core.h.
Referenced by qlcInit().
Member Data Documentation
const uint8_t Driver::DOCID_ORDER_TYPE_COUNT = 3 static
Definition at line 366 of file xapian_core.h.
Referenced by fillEnquire().
const Xapian::Enquire::docid_order Driver::DOCID_ORDER_TYPES static
Initial value:
 {
     Xapian::Enquire::ASCENDING,
     Xapian::Enquire::DESCENDING,
     Xapian::Enquire::DONT_CARE
}
Definition at line 369 of file xapian_core.h.
Referenced by fillEnquire().
const int Driver::GENERATOR_AND_TEXT_DEFAULT_FEATURES = 50 static
Reset settings to default flag.
Definition at line 345 of file xapian_core.h.
Referenced by decodeGeneratorFeatureFlags().
const int Driver::GENERATOR_AND_TEXT_FEATURES_DELIM = 50 static
Used to separate generator and text features.
Definition at line 336 of file xapian_core.h.
Referenced by decodeGeneratorFeatureFlags(), and idToTextFeature().
const unsigned Driver::GENERATOR_DEFAULT_FEATURES = 0 static
Default flags.
Definition at line 339 of file xapian_core.h.
Referenced by decodeGeneratorFeatureFlags().
const uint8_t Driver::GENERATOR_FEATURE_COUNT = 2 static
Definition at line 333 of file xapian_core.h.
Referenced by idToGeneratorFeature().
const unsigned Driver::GENERATOR_FEATURES static
Initial value:
 {
        0,
     Xapian::TermGenerator::FLAG_SPELLING,
}
Definition at line 330 of file xapian_core.h.
Referenced by idToGeneratorFeature().
Xapian::Database Driver::m_db private
Definition at line 27 of file xapian_core.h.
Referenced by databaseInfo(), deleteDocument(), enquire(), getDocument(), getDocumentById(), getLastDocId(), handleCommand(), isDocumentExist(), matchSet(), open(), qlcInit(), query(), and setDatabaseAgain().
Xapian::TermGenerator Driver::m_default_generator private
Definition at line 33 of file xapian_core.h.
Referenced by addSpelling(), applyDocument(), readGenerator(), setDatabaseAgain(), and setDefaultStemmer().
TermGeneratorFactory Driver::m_default_generator_factory private
Definition at line 38 of file xapian_core.h.
Referenced by readGenerator(), selectGenerator(), setDatabaseAgain(), and setDefaultStemmer().
Xapian::QueryParser Driver::m_default_parser private
Definition at line 31 of file xapian_core.h.
Referenced by readParser(), setDatabaseAgain(), setDefaultPrefixes(), and setDefaultStemmer().
QueryParserFactory Driver::m_default_parser_factory private
Definition at line 36 of file xapian_core.h.
Referenced by readParser(), selectParser(), setDatabaseAgain(), setDefaultPrefixes(), and setDefaultStemmer().
Xapian::Stem Driver::m_default_stemmer private
Definition at line 29 of file xapian_core.h.
Referenced by setDefaultStemmer().
MemoryManager& Driver::m_mm private
Definition at line 52 of file xapian_core.h.
Referenced by applyDocumentSchema(), retrieveDocumentSchema(), retrieveTermSchema(), and testMemory().
unsigned Driver::m_number_of_databases private
It is different for each port. It is a manager of ObjectRegisters.
Definition at line 51 of file xapian_core.h.
Referenced by docid_sub(), MSetQlcTable::lookup(), open(), and subdb_num().
Xapian::TermGenerator Driver::m_standard_generator private
Definition at line 34 of file xapian_core.h.
Referenced by setDatabaseAgain().
TermGeneratorFactory Driver::m_standard_generator_factory private
Definition at line 39 of file xapian_core.h.
Referenced by selectGenerator(), and setDatabaseAgain().
Xapian::QueryParser Driver::m_standard_parser private
Definition at line 32 of file xapian_core.h.
Referenced by setDatabaseAgain().
QueryParserFactory Driver::m_standard_parser_factory private
Definition at line 37 of file xapian_core.h.
Referenced by selectParser(), and setDatabaseAgain().
Resource::Factory Driver::m_store private
It is global. It knows how to create user customized resources.
Definition at line 45 of file xapian_core.h.
Referenced by createQueryParser(), createResource(), document(), documentInfoResource(), enquire(), extractEnquire(), extractKeyMaker(), extractMSet(), extractQuery(), extractQueryParser(), extractRangeProcessor(), extractSpy(), extractStem(), extractStopper(), extractWeight(), extractWritableSpy(), getResourceConstructors(), matchSet(), matchSpyInfo(), msetInfo(), parseString(), qlcInit(), qlcLookup(), qlcNext(), readParser(), releaseResource(), and releaseResources().
Xapian::WritableDatabase Driver::m_wdb private
Definition at line 28 of file xapian_core.h.
Referenced by addDocument(), addSpelling(), cancelTransaction(), commitTransaction(), deleteDocument(), getDocument(), handleCommand(), open(), replaceDocument(), replaceOrCreateDocument(), setDatabaseAgain(), setMetadata(), startTransaction(), and updateDocument().
XAPIAN_ERLANG_NS_BEGIN const uint8_t Driver::PARSER_FEATURE_COUNT = 13 static
Prefix m_ (member) for properties means that property is private.
Definition at line 327 of file xapian_core.h.
Referenced by idToParserFeature().
const unsigned Driver::PARSER_FEATURES static
Initial value:
 {
        0,
     Xapian::QueryParser::FLAG_BOOLEAN,
     Xapian::QueryParser::FLAG_PHRASE,
     Xapian::QueryParser::FLAG_LOVEHATE,
     Xapian::QueryParser::FLAG_BOOLEAN_ANY_CASE,
     Xapian::QueryParser::FLAG_WILDCARD,
     Xapian::QueryParser::FLAG_PURE_NOT,
     Xapian::QueryParser::FLAG_PARTIAL,
     Xapian::QueryParser::FLAG_SPELLING_CORRECTION,
     Xapian::QueryParser::FLAG_SYNONYM,
     Xapian::QueryParser::FLAG_AUTO_SYNONYMS,
     Xapian::QueryParser::FLAG_AUTO_MULTIWORD_SYNONYMS,
     Xapian::QueryParser::FLAG_DEFAULT
}
Definition at line 324 of file xapian_core.h.
Referenced by idToParserFeature().
const Xapian::QueryParser::stem_strategy Driver::STEM_STRATEGIES static
Initial value:
 {
     Xapian::QueryParser::STEM_NONE,
     Xapian::QueryParser::STEM_SOME,
     Xapian::QueryParser::STEM_ALL
}
Definition at line 357 of file xapian_core.h.
Referenced by readStemmingStrategy().
const uint8_t Driver::STEM_STRATEGY_COUNT = 3 static
Definition at line 354 of file xapian_core.h.
Referenced by readStemmingStrategy().
const unsigned Driver::TEXT_DEFAULT_FEATURES = Driver::TEXT_FLAG_POSITIONS static
Definition at line 342 of file xapian_core.h.
Referenced by decodeGeneratorFeatureFlags().
const uint8_t Driver::TEXT_FEATURE_COUNT = 2 static
Definition at line 351 of file xapian_core.h.
Referenced by idToTextFeature().
const unsigned Driver::TEXT_FEATURES static
Initial value:
 {
        0,
     Driver::TEXT_FLAG_POSITIONS,
}
Definition at line 348 of file xapian_core.h.
Referenced by idToTextFeature().
The documentation for this class was generated from the following files:
c_src/common/xapian_core.h
c_src/common/xapian_core.cpp