Xapian Erlang Binding: ResourceManager Class Reference
ResourceManager Class Reference
#include <user_resources.h>
Public Member Functions
ResourceManager (ResourceGenerator &generator)
void set_database (Xapian::Database &db)
Xapian::Database & get_database ()
ResourceObjectP get (ResourceValidObjectType type, ParamDecoder &params)
ObjectBaseRegister & get (uint8_t type)
ObjectBaseRegister & get (ResourceValidObjectType type)
void add (ResourceValidObjectType type, ObjectBaseRegister *reg)
ResourceObjectNum createAndRegister (ParamDecoder &params)
Private Attributes
ResourceGenerator & m_generator
Xapian::Database * mp_db
ObjectBaseRegister * m_stores [ResourceType::LAST_TYPE+1]
Detailed Description
Resource manager is single for each port (for each gen_server). It contains function for searching among active resources.
Definition at line 179 of file user_resources.h.
Constructor & Destructor Documentation
ResourceManager::ResourceManager (ResourceGenerator & generator) inline
Definition at line 196 of file user_resources.h.
References mp_db.
Member Function Documentation
void ResourceManager::add (ResourceValidObjectType type, ObjectBaseRegister * reg) inline
Add an object register. Called by the driver.
Definition at line 255 of file user_resources.h.
References m_stores.
Referenced by Driver::Driver().
ResourceObjectNum ResourceManager::createAndRegister (ParamDecoder & params) inline
Create and register an object for driver. Return an id of new object.
Definition at line 266 of file user_resources.h.
References ResourceGenerator::create(), m_generator, ObjectBaseRegister::putVoidPointer(), ResourceObjectP, and ResourceType::validateType().
Referenced by Driver::createResource().
ResourceObjectP ResourceManager::get (ResourceValidObjectType type, ParamDecoder & params) inline
Get a resource object.
Definition at line 221 of file user_resources.h.
References ObjectBaseRegister::getVoidPointer(), m_stores, and ResourceType::validateType().
Referenced by Driver::getRegisterByType().
ObjectBaseRegister& ResourceManager::get (uint8_t type) inline
Get a resource manager. used by the driver.
Definition at line 234 of file user_resources.h.
References ResourceType::validateType().
ObjectBaseRegister& ResourceManager::get (ResourceValidObjectType type) inline
Return an object which contains resources.
Definition at line 245 of file user_resources.h.
References m_stores.
Xapian::Database& ResourceManager::get_database () inline
Definition at line 209 of file user_resources.h.
References mp_db.
void ResourceManager::set_database (Xapian::Database & db) inline
Definition at line 203 of file user_resources.h.
References mp_db.
Referenced by Driver::open().
Member Data Documentation
ResourceGenerator& ResourceManager::m_generator private
Definition at line 182 of file user_resources.h.
Referenced by createAndRegister().
ObjectBaseRegister* ResourceManager::m_stores[ResourceType::LAST_TYPE+1] private
Pointers on stores of opened resources objects. If LAST_TYPE is 2, then the size of this array is 3.
Definition at line 192 of file user_resources.h.
Referenced by add(), and get().
Xapian::Database* ResourceManager::mp_db private
Definition at line 185 of file user_resources.h.
Referenced by get_database(), ResourceManager(), and set_database().
The documentation for this class was generated from the following file:
c_src/user_resources.h