Xapian Erlang Binding: Base Class Reference
Base Class Reference
#include <base.h>
Public Member Functions
Base ()
virtual ~Base ()
void incref ()
void decref ()
void attach (Element &child)
void attachContext (Element &context)
virtual std::string type ()
virtual operator Xapian::MSet & ()
virtual operator Xapian::KeyMaker & ()
virtual operator Xapian::Enquire & ()
virtual operator QlcTable & ()
virtual operator Xapian::Weight & ()
virtual operator Xapian::Query & ()
virtual operator Xapian::MatchDecider & ()
virtual operator Xapian::ExpandDecider & ()
virtual operator Xapian::ValueRangeProcessor & ()
virtual operator Xapian::QueryParser & ()
virtual operator Xapian::Stopper & ()
virtual operator Xapian::Stem & ()
virtual operator Xapian::ValueCountMatchSpy & ()
virtual operator Xapian::MatchSpy & ()
virtual operator Xapian::Document & ()
virtual operator Extension::ValueCountMatchSpy & ()
virtual void finalize ()
virtual bool is_finalized ()
Private Member Functions
Base & operator= (const Base &)
Base (const Base &)
Private Attributes
unsigned m_counter
std::vector< Element > m_children
bool mb_attached
Detailed Description
Definition at line 40 of file base.h.
Constructor & Destructor Documentation
Base::Base (const Base &) inline private
Copy constructor. Copy is not allowed.
Definition at line 52 of file base.h.
Base::Base () inline
Definition at line 55 of file base.h.
virtual Base::~Base () inline virtual
Definition at line 57 of file base.h.
Member Function Documentation
void Base::attach (Element & child) inline
Definition at line 69 of file base.h.
References Element::get(), m_children, mb_attached, and type().
Referenced by attachContext().
void Base::attachContext (Element & context) inline
Definition at line 83 of file base.h.
References attach(), Element::get(), m_children, and mb_attached.
void Base::decref () inline
Definition at line 60 of file base.h.
References m_counter.
virtual void Base::finalize () inline virtual
Reimplemented in MatchSpy.
Definition at line 179 of file base.h.
References type().
void Base::incref () inline
Definition at line 59 of file base.h.
References m_counter.
virtual bool Base::is_finalized () inline virtual
Reimplemented in MatchSpy.
Definition at line 184 of file base.h.
References type().
virtual Base::operator Extension::ValueCountMatchSpy & () inline virtual
Reimplemented in ValueCountMatchSpy.
Definition at line 173 of file base.h.
References type().
virtual Base::operator QlcTable & () inline virtual
Definition at line 112 of file base.h.
References type().
virtual Base::operator Xapian::Document & () inline virtual
Reimplemented in Document.
Definition at line 167 of file base.h.
References type().
virtual Base::operator Xapian::Enquire & () inline virtual
Reimplemented in Enquire.
Definition at line 107 of file base.h.
References type().
virtual Base::operator Xapian::ExpandDecider & () inline virtual
Definition at line 132 of file base.h.
References type().
virtual Base::operator Xapian::KeyMaker & () inline virtual
Reimplemented in KeyMaker.
Definition at line 102 of file base.h.
References type().
virtual Base::operator Xapian::MatchDecider & () inline virtual
Definition at line 127 of file base.h.
References type().
virtual Base::operator Xapian::MatchSpy & () inline virtual
Reimplemented in MatchSpy.
Definition at line 162 of file base.h.
References type().
virtual Base::operator Xapian::MSet & () inline virtual
Reimplemented in MSet.
Definition at line 97 of file base.h.
References type().
virtual Base::operator Xapian::Query & () inline virtual
Reimplemented in Query.
Definition at line 122 of file base.h.
References type().
virtual Base::operator Xapian::QueryParser & () inline virtual
Reimplemented in QueryParser.
Definition at line 142 of file base.h.
References type().
virtual Base::operator Xapian::Stem & () inline virtual
Definition at line 152 of file base.h.
References type().
virtual Base::operator Xapian::Stopper & () inline virtual
Reimplemented in Stopper.
Definition at line 147 of file base.h.
References type().
virtual Base::operator Xapian::ValueCountMatchSpy & () inline virtual
Reimplemented in ValueCountMatchSpy.
Definition at line 157 of file base.h.
References type().
virtual Base::operator Xapian::ValueRangeProcessor & () inline virtual
Reimplemented in ValueRangeProcessor.
Definition at line 137 of file base.h.
References type().
virtual Base::operator Xapian::Weight & () inline virtual
Reimplemented in Weight.
Definition at line 117 of file base.h.
References type().
Base& Base::operator= (const Base &) inline private
Assignment operator. Assignment is not allowed.
Definition at line 48 of file base.h.
virtual std::string Base::type () inline virtual
Reimplemented in ValueCountMatchSpy, MatchSpy, Document, Enquire, KeyMaker, MSet, QlcTable, Query, QueryParser, Stopper, ValueRangeProcessor, and Weight.
Definition at line 92 of file base.h.
Referenced by attach(), finalize(), is_finalized(), operator Extension::ValueCountMatchSpy &(), operator QlcTable &(), operator Xapian::Document &(), operator Xapian::Enquire &(), operator Xapian::ExpandDecider &(), operator Xapian::KeyMaker &(), operator Xapian::MatchDecider &(), operator Xapian::MatchSpy &(), operator Xapian::MSet &(), operator Xapian::Query &(), operator Xapian::QueryParser &(), operator Xapian::Stem &(), operator Xapian::Stopper &(), operator Xapian::ValueCountMatchSpy &(), operator Xapian::ValueRangeProcessor &(), and operator Xapian::Weight &().
Member Data Documentation
std::vector<Element> Base::m_children private
Definition at line 43 of file base.h.
Referenced by attach(), and attachContext().
unsigned Base::m_counter private
Definition at line 42 of file base.h.
Referenced by decref(), and incref().
bool Base::mb_attached private
Definition at line 44 of file base.h.
Referenced by attach(), and attachContext().
The documentation for this class was generated from the following file:
c_src/common/resource/controller/base.h