Xapian Erlang Binding: Helpers Class Reference
Helpers Class Reference
#include <xapian_helpers.h>
Static Public Member Functions
static Xapian::termcount getTermFrequency (Xapian::Document &doc, const std::string &tname)
static Xapian::termcount getExistedTermFrequency (Xapian::Document &doc, const std::string &tname)
static void tryRemoveValue (Xapian::Document &doc, Xapian::valueno slot_no, bool ignoreErrors)
static void tryRemoveTerm (Xapian::Document &doc, const std::string &tname, bool ignoreErrors)
static void tryRemovePosting (Xapian::Document &doc, const std::string &tname, Xapian::termpos tpos, Xapian::termcount wdf_inc, bool ignoreErrors)
static void tryDecreaseWDF (Xapian::Document &doc, const std::string &tname, Xapian::termcount wdf, bool ignoreErrors)
static void trySetWDF (Xapian::Document &doc, const std::string &tname, Xapian::termcount wdf, bool ignoreErrors)
static void tryClearTermPositions (Xapian::Document &doc, const std::string &tname, bool ignoreErrors)
static void clearTermPositions (Xapian::Document &doc, const std::string &tname)
static void clearTermPositions (Xapian::Document &doc)
static bool isValueExist (Xapian::Document &doc, Xapian::valueno slot_no)
static bool isTermExist (Xapian::Document &doc, const std::string &tname)
static bool isPostingExist (Xapian::Document &doc, const std::string &tname, Xapian::termpos term_pos)
static Xapian::termcount getSpellingFrequency (Xapian::Database &wdb, const std::string &tname)
static void trySetSpellingFreq (Xapian::WritableDatabase &wdb, const std::string &tname, Xapian::termcount freq, bool ignoreErrors)
static void tryDecreaseSpellingFreq (Xapian::WritableDatabase &wdb, const std::string &tname, Xapian::termcount freq, bool ignoreErrors)
static void tryRemoveSpelling (Xapian::WritableDatabase &wdb, const std::string &tname, bool ignoreErrors)
static bool isSpellingExist (Xapian::Database &db, const std::string &tname)
Detailed Description
Definition at line 11 of file xapian_helpers.h.
Member Function Documentation
void Helpers::clearTermPositions (Xapian::Document & doc, const std::string & tname) static
Definition at line 163 of file xapian_helpers.cpp.
References getExistedTermFrequency().
Referenced by Driver::applyDocument(), and tryClearTermPositions().
void Helpers::clearTermPositions (Xapian::Document & doc) static
Definition at line 174 of file xapian_helpers.cpp.
Xapian::termcount Helpers::getExistedTermFrequency (Xapian::Document & doc, const std::string & tname) static
Definition at line 34 of file xapian_helpers.cpp.
Referenced by clearTermPositions().
Xapian::termcount Helpers::getSpellingFrequency (Xapian::Database & wdb, const std::string & tname) static
Definition at line 256 of file xapian_helpers.cpp.
Referenced by SpellingFreqManipulation::current_frequency(), and Driver::handleSpelling().
XAPIAN_ERLANG_NS_BEGIN Xapian::termcount Helpers::getTermFrequency (Xapian::Document & doc, const std::string & tname) static
Definition at line 15 of file xapian_helpers.cpp.
Referenced by Driver::handleTerm(), and WdfManipulation::set_wdf().
bool Helpers::isPostingExist (Xapian::Document & doc, const std::string & tname, Xapian::termpos term_pos) static
Definition at line 224 of file xapian_helpers.cpp.
Referenced by Driver::handlePosting(), and WdfManipulation::WdfManipulation().
bool Helpers::isSpellingExist (Xapian::Database & db, const std::string & tname) static
Definition at line 274 of file xapian_helpers.cpp.
Referenced by Driver::handleSpelling(), and SpellingFreqManipulation::SpellingFreqManipulation().
bool Helpers::isTermExist (Xapian::Document & doc, const std::string & tname) static
Definition at line 209 of file xapian_helpers.cpp.
Referenced by Driver::handleTerm(), and WdfManipulation::WdfManipulation().
bool Helpers::isValueExist (Xapian::Document & doc, Xapian::valueno slot_no) static
Definition at line 194 of file xapian_helpers.cpp.
Referenced by Driver::handleValue().
void Helpers::tryClearTermPositions (Xapian::Document & doc, const std::string & tname, bool ignoreErrors) static
Definition at line 148 of file xapian_helpers.cpp.
References clearTermPositions().
Referenced by Driver::applyDocument().
void Helpers::tryDecreaseSpellingFreq (Xapian::WritableDatabase & wdb, const std::string & tname, Xapian::termcount freq, bool ignoreErrors) static
Definition at line 315 of file xapian_helpers.cpp.
References SpellingFreqManipulation::dec_frequency().
Referenced by Driver::addSpelling().
void Helpers::tryDecreaseWDF (Xapian::Document & doc, const std::string & tname, Xapian::termcount wdf, bool ignoreErrors) static
Definition at line 98 of file xapian_helpers.cpp.
References WdfManipulation::dec_wdf().
Referenced by Driver::applyDocument().
void Helpers::tryRemovePosting (Xapian::Document & doc, const std::string & tname, Xapian::termpos tpos, Xapian::termcount wdf_inc, bool ignoreErrors) static
Definition at line 80 of file xapian_helpers.cpp.
Referenced by Driver::handlePosting().
void Helpers::tryRemoveSpelling (Xapian::WritableDatabase & wdb, const std::string & tname, bool ignoreErrors) static
Definition at line 341 of file xapian_helpers.cpp.
References SpellingFreqManipulation::clear_frequency().
Referenced by Driver::handleSpelling().
void Helpers::tryRemoveTerm (Xapian::Document & doc, const std::string & tname, bool ignoreErrors) static
Definition at line 67 of file xapian_helpers.cpp.
Referenced by Driver::handleTerm().
void Helpers::tryRemoveValue (Xapian::Document & doc, Xapian::valueno slot_no, bool ignoreErrors) static
Definition at line 54 of file xapian_helpers.cpp.
Referenced by Driver::handleValue().
void Helpers::trySetSpellingFreq (Xapian::WritableDatabase & wdb, const std::string & tname, Xapian::termcount freq, bool ignoreErrors) static
Definition at line 289 of file xapian_helpers.cpp.
References SpellingFreqManipulation::set_frequency().
Referenced by Driver::addSpelling().
void Helpers::trySetWDF (Xapian::Document & doc, const std::string & tname, Xapian::termcount wdf, bool ignoreErrors) static
Definition at line 123 of file xapian_helpers.cpp.
References WdfManipulation::set_wdf().
Referenced by Driver::applyDocument().
The documentation for this class was generated from the following files:
c_src/common/xapian_helpers.h
c_src/common/xapian_helpers.cpp