Xapian Erlang Binding: QueryParserFactory Class Reference
QueryParserFactory Class Reference
#include <query_parser_factory.h>
Public Member Functions
void set_stemmer (const Xapian::Stem &stemmer)
void set_database (const Xapian::Database &db)
void add_prefix (const std::string &field, const std::string &prefix)
void add_boolean_prefix (const std::string &field, const std::string &prefix, bool exclusive)
operator Xapian::QueryParser ()
Private Attributes
Xapian::Database m_db
Xapian::Stem m_stemmer
std::vector< PrefixInternal > m_prefixes
Detailed Description
It is here, because QueryParser cannot be cloned.
Definition at line 47 of file query_parser_factory.h.
Member Function Documentation
void QueryParserFactory::add_boolean_prefix (const std::string & field, const std::string & prefix, bool exclusive) inline
Definition at line 70 of file query_parser_factory.h.
References m_prefixes.
Referenced by Driver::addPrefix().
void QueryParserFactory::add_prefix (const std::string & field, const std::string & prefix) inline
Definition at line 64 of file query_parser_factory.h.
References m_prefixes.
Referenced by Driver::addPrefix().
QueryParserFactory::operator Xapian::QueryParser () inline
Definition at line 77 of file query_parser_factory.h.
References m_db, m_prefixes, and m_stemmer.
void QueryParserFactory::set_database (const Xapian::Database & db) inline
Definition at line 59 of file query_parser_factory.h.
References m_db.
Referenced by Driver::setDatabaseAgain().
void QueryParserFactory::set_stemmer (const Xapian::Stem & stemmer) inline
Definition at line 54 of file query_parser_factory.h.
References m_stemmer.
Referenced by Driver::setDefaultStemmer().
Member Data Documentation
Xapian::Database QueryParserFactory::m_db private
Definition at line 49 of file query_parser_factory.h.
Referenced by operator Xapian::QueryParser(), and set_database().
std::vector< PrefixInternal > QueryParserFactory::m_prefixes private
Definition at line 51 of file query_parser_factory.h.
Referenced by add_boolean_prefix(), add_prefix(), and operator Xapian::QueryParser().
Xapian::Stem QueryParserFactory::m_stemmer private
Definition at line 50 of file query_parser_factory.h.
Referenced by operator Xapian::QueryParser(), and set_stemmer().
The documentation for this class was generated from the following file:
c_src/common/query_parser_factory.h