Xapian Erlang Binding: DriverController Class Reference
DriverController Class Reference
#include <xapian_drvctrl.h>
Static Public Member Functions
static int init ()
static void finish ()
static ErlDrvData start (ErlDrvPort port, char *)
static void stop (ErlDrvData drv_data)
static ErlDrvSSizeT control (ErlDrvData drv_data, unsigned int command, char *buf, ErlDrvSizeT len, char **rbuf, ErlDrvSizeT rlen)
Detailed Description
Definition at line 14 of file xapian_drvctrl.h.
Member Function Documentation
ErlDrvSSizeT DriverController::control (ErlDrvData drv_data, unsigned int command, char * buf, ErlDrvSizeT len, char ** rbuf, ErlDrvSizeT rlen) static
Definition at line 73 of file xapian_drvctrl.cpp.
References ResultEncoder::finalize(), ResultEncoder::finalSize(), Driver::handleCommand(), and ResultEncoder::isExtended().
void DriverController::finish () static
The driver is unloaded. This is called only once.
Delete global variables
Definition at line 37 of file xapian_drvctrl.cpp.
References gp_driverMemoryManager.
int DriverController::init () static
The driver is loaded. This is called only once.
Create global variables
Definition at line 23 of file xapian_drvctrl.cpp.
ErlDrvData DriverController::start (ErlDrvPort port, char *) static
Here we do some initialization, start is called from `open_port'. The drv_data will be passed to control and stop. This is called multiple times.
Definition at line 47 of file xapian_drvctrl.cpp.
void DriverController::stop (ErlDrvData drv_data) static
This is called multiple times.
Definition at line 60 of file xapian_drvctrl.cpp.
The documentation for this class was generated from the following files:
c_src/driver/xapian_drvctrl.h
c_src/driver/xapian_drvctrl.cpp