Xapian Erlang Binding: ResultEncoder Class Reference
ResultEncoder Class Reference
#include <result_encoder.h>
Public Member Functions
ResultEncoder (MemoryManager &mm)
void setBuffer (char *rbuf, const size_t rlen)
ResultEncoder (MemoryManager &mm, char *rbuf, const size_t rlen)
bool maybe (bool is_exists)
void put (const char *term, const size_t term_len)
void finalize (char *)
size_t finalSize () const
bool isExtended () const
void clear ()
void reset ()
Appends variables to the buffer.
ResultEncoder & operator<< (const std::string str)
ResultEncoder & operator<< (const char *str)
ResultEncoder & operator<< (uint32_t value)
ResultEncoder & operator<< (uint8_t value)
ResultEncoder & operator<< (double value)
Private Member Functions
DataSegment * alloc (size_t size)
void free (DataSegment *&pos)
Private Attributes
MemoryManager & m_mm
char * m_current_buf
size_t m_current_len
char * m_default_buf
size_t m_default_len
size_t m_left_len
DataSegment * m_first_segment
DataSegment * m_last_segment
Detailed Description
If the driver wants to return data, it should return it in rbuf. When control is called, *rbuf points to a default buffer of rlen bytes, which can be used to return data. Data is returned different depending on the port control flags (those that are set with set_port_control_flags).
Definition at line 27 of file result_encoder.h.
Constructor & Destructor Documentation
ResultEncoder::ResultEncoder (MemoryManager & mm) inline
Definition at line 66 of file result_encoder.h.
ResultEncoder::ResultEncoder (MemoryManager & mm, char * rbuf, const size_t rlen) inline
Definition at line 76 of file result_encoder.h.
References setBuffer().
Member Function Documentation
DataSegment * ResultEncoder::alloc (size_t size) private
Allocate a new data segment and return a pointer on it.
Definition at line 113 of file result_encoder.cpp.
References MemoryManager::alloc(), m_mm, and SIZE_OF_SEGMENT.
Referenced by put().
void ResultEncoder::clear ()
Clear the state of the object.
Definition at line 197 of file result_encoder.cpp.
References free(), m_current_buf, m_current_len, m_default_len, m_first_segment, m_last_segment, and DataSegment::next.
Referenced by reset(), and run().
void ResultEncoder::finalize (char * dest)
Merge all segments together. Data will be reseted. buf is used to copy data.
Definition at line 256 of file result_encoder.cpp.
References DataSegment::data, free(), isExtended(), m_current_buf, m_current_len, m_default_buf, m_default_len, m_first_segment, m_last_segment, m_left_len, DataSegment::next, and DataSegment::size.
Referenced by DriverController::control(), and run().
size_t ResultEncoder::finalSize () const
Returns the result's length.
Definition at line 302 of file result_encoder.cpp.
References m_current_len.
Referenced by DriverController::control(), and run().
void ResultEncoder::free (DataSegment *& pos) private
Deallocate the data segment.
Definition at line 123 of file result_encoder.cpp.
References MemoryManager::free(), and m_mm.
Referenced by clear(), and finalize().
bool ResultEncoder::isExtended () const
Returns true, if the existed buffer is too small.
Return true, if this class allocated memory.
Definition at line 241 of file result_encoder.cpp.
References m_current_len, and m_default_len.
Referenced by DriverController::control(), finalize(), and run().
bool ResultEncoder::maybe (bool is_exists)
Definition at line 307 of file result_encoder.cpp.
References PUT_VALUE.
ResultEncoder & ResultEncoder::operator<< (const std::string str)
Definition at line 69 of file result_encoder.cpp.
References put(), and PUT_VALUE.
ResultEncoder & ResultEncoder::operator<< (const char * str)
Definition at line 79 of file result_encoder.cpp.
References put(), and PUT_VALUE.
ResultEncoder & ResultEncoder::operator<< (uint32_t value)
Definition at line 89 of file result_encoder.cpp.
References PUT_VALUE.
ResultEncoder & ResultEncoder::operator<< (uint8_t value)
Definition at line 97 of file result_encoder.cpp.
References PUT_VALUE.
ResultEncoder & ResultEncoder::operator<< (double value)
Definition at line 105 of file result_encoder.cpp.
References PUT_VALUE.
void ResultEncoder::put (const char * term, const size_t term_len)
It is used by << operators. Appends a block of data of size term_len to the result.
Definition at line 131 of file result_encoder.cpp.
References alloc(), DataSegment::data, m_current_buf, m_current_len, m_default_buf, m_default_len, m_first_segment, m_last_segment, m_left_len, DataSegment::next, RESERVED_LEN, and DataSegment::size.
Referenced by operator<<().
void ResultEncoder::reset ()
Reset to the state after the setBuffer call.
Definition at line 229 of file result_encoder.cpp.
References clear(), m_default_buf, m_default_len, and setBuffer().
void ResultEncoder::setBuffer (char * rbuf, const size_t rlen)
Set the internal pointer on the client-managed block of data.
Definition at line 55 of file result_encoder.cpp.
References m_current_buf, m_current_len, m_default_buf, m_default_len, m_first_segment, and m_left_len.
Referenced by reset(), ResultEncoder(), and run().
Member Data Documentation
char* ResultEncoder::m_current_buf private
Definition at line 33 of file result_encoder.h.
Referenced by clear(), finalize(), put(), and setBuffer().
size_t ResultEncoder::m_current_len private
Definition at line 36 of file result_encoder.h.
Referenced by clear(), finalize(), finalSize(), isExtended(), put(), and setBuffer().
char* ResultEncoder::m_default_buf private
Definition at line 39 of file result_encoder.h.
Referenced by finalize(), put(), reset(), and setBuffer().
size_t ResultEncoder::m_default_len private
Definition at line 41 of file result_encoder.h.
Referenced by clear(), finalize(), isExtended(), put(), reset(), and setBuffer().
DataSegment* ResultEncoder::m_first_segment private
Definition at line 48 of file result_encoder.h.
Referenced by clear(), finalize(), put(), and setBuffer().
DataSegment* ResultEncoder::m_last_segment private
Definition at line 51 of file result_encoder.h.
Referenced by clear(), finalize(), and put().
size_t ResultEncoder::m_left_len private
Definition at line 44 of file result_encoder.h.
Referenced by finalize(), put(), and setBuffer().
MemoryManager& ResultEncoder::m_mm private
Definition at line 30 of file result_encoder.h.
Referenced by alloc(), and free().
The documentation for this class was generated from the following files:
c_src/common/result_encoder.h
c_src/common/result_encoder.cpp