Xapian Erlang Binding: Generator Class Reference
Generator Class Reference
#include <generator.h>
Public Types
typedef std::vector
< Constructor * >::iterator constructor_iterator
typedef std::vector
< Constructor * >
::const_iterator const_constructor_iterator
Public Member Functions
Generator ()
void add (Constructor *p_constructor)
Element create (Register &manager, ParamDecoder &params)
~Generator ()
void registerCallbacks ()
constructor_iterator constructor_begin ()
const_constructor_iterator constructor_begin () const
constructor_iterator constructor_end ()
const_constructor_iterator constructor_end () const
Private Types
typedef std::vector
< Constructor * > Constructors
Private Member Functions
Generator & operator= (const Generator &)
Generator (const Generator &)
bool isExists (uint32_t constructor_num)
Private Attributes
Constructors m_constructors
Registered constructors.
Detailed Description
Definition at line 20 of file generator.h.
Member Typedef Documentation
typedef std::vector<Constructor*>::const_iterator Generator::const_constructor_iterator
Definition at line 72 of file generator.h.
typedef std::vector<Constructor*>::iterator Generator::constructor_iterator
Definition at line 71 of file generator.h.
typedef std::vector<Constructor*> Generator::Constructors private
Definition at line 22 of file generator.h.
Constructor & Destructor Documentation
Generator::Generator (const Generator &) inline private
Copy constructor. Copy is not allowed.
Definition at line 32 of file generator.h.
Generator::Generator () inline
Definition at line 42 of file generator.h.
Generator::~Generator () inline
Definition at line 54 of file generator.h.
References m_constructors.
Member Function Documentation
void Generator::add (Constructor * p_constructor) inline
Definition at line 46 of file generator.h.
References m_constructors.
constructor_iterator Generator::constructor_begin () inline
Definition at line 75 of file generator.h.
References m_constructors.
Referenced by Factory::getResourceConstructors().
const_constructor_iterator Generator::constructor_begin () const inline
Definition at line 79 of file generator.h.
References m_constructors.
constructor_iterator Generator::constructor_end () inline
Definition at line 83 of file generator.h.
References m_constructors.
Referenced by Factory::getResourceConstructors().
const_constructor_iterator Generator::constructor_end () const inline
Definition at line 87 of file generator.h.
References m_constructors.
XAPIAN_RESOURCE_NS_BEGIN Element Generator::create (Register & manager, ParamDecoder & params)
Definition at line 9 of file generator.cpp.
References Constructor::call(), isExists(), and m_constructors.
Referenced by Factory::create(), Factory::extract(), and Factory::skip().
bool Generator::isExists (uint32_t constructor_num) inline private
Definition at line 35 of file generator.h.
References m_constructors.
Referenced by create().
Generator& Generator::operator= (const Generator &) inline private
Assignment operator. Assignment is not allowed.
Definition at line 28 of file generator.h.
void Generator::registerCallbacks ()
Definition at line 148 of file cons.cpp.
References createBM25Weight(), createBoolWeight(), createDateValueRangeProcessor3(), createDateValueRangeProcessor5(), createMultiValueKeyMaker(), createNumberValueRangeProcessor1(), createNumberValueRangeProcessor3(), createSimpleStopper(), createStringValueRangeProcessor1(), createStringValueRangeProcessor3(), createTradWeight(), and createValueCountMatchSpy().
Referenced by Factory::Factory().
Member Data Documentation
Constructors Generator::m_constructors private
Registered constructors.
Definition at line 24 of file generator.h.
Referenced by add(), constructor_begin(), constructor_end(), create(), isExists(), and ~Generator().
The documentation for this class was generated from the following files:
c_src/common/resource/generator.h
c_src/common/resource/cons.cpp
c_src/common/resource/generator.cpp