Xapian Erlang Binding: TermQlcTable Class Reference
TermQlcTable Class Reference
#include <qlc.h>
Public Member Functions
TermQlcTable (Driver &driver, TermGenerator::Iterator *gen, const ParamDecoderController &controller)
~TermQlcTable ()
uint32_t size ()
void getPage (ResultEncoder &, uint32_t from, uint32_t count)
void lookup (PR)
Public Member Functions inherited from QlcTable
QlcTable (Driver &driver)
virtual ~QlcTable ()
QlcTable (XAPIAN_ERLANG_NS::QlcTable *p_table)
~QlcTable ()
operator XAPIAN_ERLANG_NS::QlcTable & ()
std::string type ()
Public Member Functions inherited from Base
Base ()
virtual ~Base ()
void incref ()
void decref ()
void attach (Element &child)
void attachContext (Element &context)
virtual operator Xapian::MSet & ()
virtual operator Xapian::KeyMaker & ()
virtual operator Xapian::Enquire & ()
virtual operator QlcTable & ()
virtual operator Xapian::Weight & ()
virtual operator Xapian::Query & ()
virtual operator Xapian::MatchDecider & ()
virtual operator Xapian::ExpandDecider & ()
virtual operator Xapian::ValueRangeProcessor & ()
virtual operator Xapian::QueryParser & ()
virtual operator Xapian::Stopper & ()
virtual operator Xapian::Stem & ()
virtual operator Xapian::ValueCountMatchSpy & ()
virtual operator Xapian::MatchSpy & ()
virtual operator Xapian::Document & ()
virtual operator Extension::ValueCountMatchSpy & ()
virtual void finalize ()
virtual bool is_finalized ()
Private Member Functions
void goToAndCheckBorder (const uint32_t skip)
Checks out of border.
void goTo (const uint32_t skip)
void getPageKnownSize (ResultEncoder &, const uint32_t skip, const uint32_t count)
void getPageUnknownSize (ResultEncoder &, const uint32_t skip, const uint32_t count)
Private Attributes
Xapian::TermIterator m_iter
Xapian::TermIterator m_end
TermGenerator::Iterator * mp_gen
uint32_t m_current_pos
uint32_t m_size
const ParamDecoderController m_controller
Additional Inherited Members
Static Public Attributes inherited from QlcTable
static const uint8_t MORE = 1
static const uint8_t STOP = 0
static const uint8_t UNKNOWN_SIZE = 0
static const uint8_t KNOWN_SIZE = 1
Protected Attributes inherited from QlcTable
Driver & m_driver
Detailed Description
This table is base on TermGenerator::Iterator. This table is used for iterating terms in a document or for iterating values in MatchSpy. TermGenerator::Iterator knows how to init Xapian::TermIterator iterators.
Definition at line 116 of file qlc.h.
Constructor & Destructor Documentation
TermQlcTable::TermQlcTable (Driver & driver, TermGenerator::Iterator * gen, const ParamDecoderController & controller)
gen variable will be deallocated by the system (not by a programmer!). gen and the new object have the same live-time.
Definition at line 139 of file qlc.cpp.
References m_current_pos, m_end, m_iter, m_size, and mp_gen.
TermQlcTable::~TermQlcTable ()
Definition at line 310 of file qlc.cpp.
References mp_gen.
Member Function Documentation
void TermQlcTable::getPage (ResultEncoder & result, uint32_t from, uint32_t count) virtual
Skip "skip" documents. Read not more then "count" documents.
Implements QlcTable.
Definition at line 168 of file qlc.cpp.
References getPageKnownSize(), getPageUnknownSize(), and m_size.
void TermQlcTable::getPageKnownSize (ResultEncoder & result, const uint32_t skip, const uint32_t count) private
Skip skip objects from the beginning and return objects. Maximum count object will be returned. It is used, when the total size of objects is not yet known.
Definition at line 230 of file qlc.cpp.
References goTo(), QlcTable::KNOWN_SIZE, m_controller, m_current_pos, QlcTable::m_driver, m_end, m_iter, m_size, Driver::retrieveTerm(), and size().
Referenced by getPage().
void TermQlcTable::getPageUnknownSize (ResultEncoder & result, const uint32_t skip, const uint32_t count) private
Skip skip objects from the beginning and return objects. Maximum count object will be returned. It is used, when the total size of objects is known.
Definition at line 194 of file qlc.cpp.
References goToAndCheckBorder(), m_controller, m_current_pos, QlcTable::m_driver, m_end, m_iter, m_size, QlcTable::MORE, Driver::retrieveTerm(), QlcTable::STOP, and QlcTable::UNKNOWN_SIZE.
Referenced by getPage().
void TermQlcTable::goTo (const uint32_t skip) private
Skip skip objects from the beginning. It is used, when the total size of objects is known.
Definition at line 269 of file qlc.cpp.
References m_current_pos, m_end, m_iter, and mp_gen.
Referenced by getPageKnownSize(), and goToAndCheckBorder().
void TermQlcTable::goToAndCheckBorder (const uint32_t skip) private
Checks out of border.
Skip skip objects from the beginning. It is used, when the total size of objects is not yet known.
Definition at line 292 of file qlc.cpp.
References goTo(), m_current_pos, m_end, and m_iter.
Referenced by getPageUnknownSize().
void TermQlcTable::lookup (PR) virtual
Select objects by a key (by an index).
Implements QlcTable.
Definition at line 178 of file qlc.cpp.
References m_controller, m_end, mp_gen, and Driver::qlcTermIteratorLookup().
uint32_t TermQlcTable::size () virtual
Calculate, how many objects in the set. Return zero if unknown.
Implements QlcTable.
Definition at line 157 of file qlc.cpp.
References m_size.
Referenced by getPageKnownSize(), and Driver::qlcInit().
Member Data Documentation
const ParamDecoderController TermQlcTable::m_controller private
Definition at line 123 of file qlc.h.
Referenced by getPageKnownSize(), getPageUnknownSize(), and lookup().
uint32_t TermQlcTable::m_current_pos private
Definition at line 121 of file qlc.h.
Referenced by getPageKnownSize(), getPageUnknownSize(), goTo(), goToAndCheckBorder(), and TermQlcTable().
Xapian::TermIterator TermQlcTable::m_end private
Definition at line 119 of file qlc.h.
Referenced by getPageKnownSize(), getPageUnknownSize(), goTo(), goToAndCheckBorder(), lookup(), and TermQlcTable().
Xapian::TermIterator TermQlcTable::m_iter private
Definition at line 119 of file qlc.h.
Referenced by getPageKnownSize(), getPageUnknownSize(), goTo(), goToAndCheckBorder(), and TermQlcTable().
uint32_t TermQlcTable::m_size private
Definition at line 121 of file qlc.h.
Referenced by getPage(), getPageKnownSize(), getPageUnknownSize(), size(), and TermQlcTable().
TermGenerator::Iterator* TermQlcTable::mp_gen private
Definition at line 120 of file qlc.h.
Referenced by goTo(), lookup(), TermQlcTable(), and ~TermQlcTable().
The documentation for this class was generated from the following files:
c_src/common/qlc.h
c_src/common/qlc.cpp