Xapian Erlang Binding: MSetQlcTable Class Reference
MSetQlcTable Class Reference
#include <qlc.h>
Public Member Functions
MSetQlcTable (Driver &driver, Xapian::MSet &mset, const ParamDecoderController &controller)
uint32_t size ()
void getPage (ResultEncoder &, uint32_t from, uint32_t count)
void lookup (PR)
Public Member Functions inherited from QlcTable
QlcTable (Driver &driver)
virtual ~QlcTable ()
QlcTable (XAPIAN_ERLANG_NS::QlcTable *p_table)
~QlcTable ()
operator XAPIAN_ERLANG_NS::QlcTable & ()
std::string type ()
Public Member Functions inherited from Base
Base ()
virtual ~Base ()
void incref ()
void decref ()
void attach (Element &child)
void attachContext (Element &context)
virtual operator Xapian::MSet & ()
virtual operator Xapian::KeyMaker & ()
virtual operator Xapian::Enquire & ()
virtual operator QlcTable & ()
virtual operator Xapian::Weight & ()
virtual operator Xapian::Query & ()
virtual operator Xapian::MatchDecider & ()
virtual operator Xapian::ExpandDecider & ()
virtual operator Xapian::ValueRangeProcessor & ()
virtual operator Xapian::QueryParser & ()
virtual operator Xapian::Stopper & ()
virtual operator Xapian::Stem & ()
virtual operator Xapian::ValueCountMatchSpy & ()
virtual operator Xapian::MatchSpy & ()
virtual operator Xapian::Document & ()
virtual operator Extension::ValueCountMatchSpy & ()
virtual void finalize ()
virtual bool is_finalized ()
Private Attributes
Xapian::MSet m_mset
const ParamDecoderController m_controller
Additional Inherited Members
Static Public Attributes inherited from QlcTable
static const uint8_t MORE = 1
static const uint8_t STOP = 0
static const uint8_t UNKNOWN_SIZE = 0
static const uint8_t KNOWN_SIZE = 1
Protected Attributes inherited from QlcTable
Driver & m_driver
Detailed Description
This table is based on Xapian::Mset.
Definition at line 92 of file qlc.h.
Constructor & Destructor Documentation
MSetQlcTable::MSetQlcTable (Driver & driver, Xapian::MSet & mset, const ParamDecoderController & controller)
Definition at line 27 of file qlc.cpp.
Member Function Documentation
void MSetQlcTable::getPage (ResultEncoder & result, uint32_t from, uint32_t count) virtual
Skip "skip" documents. Read not more then "count" documents.
Implements QlcTable.
Definition at line 45 of file qlc.cpp.
References m_controller, QlcTable::m_driver, m_mset, Driver::retrieveDocuments(), and size().
void MSetQlcTable::lookup (PR) virtual
Select objects by a key (by an index).
Implements QlcTable.
Definition at line 73 of file qlc.cpp.
References Driver::docid_sub(), Driver::GET_DOCID, Driver::GET_MULTI_DOCID, m_controller, QlcTable::m_driver, m_mset, Driver::m_number_of_databases, QlcTable::MORE, Driver::selectEncoderAndRetrieveDocument(), and QlcTable::STOP.
uint32_t MSetQlcTable::size () virtual
It counts the total count of objects in the set (in the table).
Implements QlcTable.
Definition at line 34 of file qlc.cpp.
References m_mset.
Referenced by getPage(), and Driver::qlcInit().
Member Data Documentation
const ParamDecoderController MSetQlcTable::m_controller private
Definition at line 95 of file qlc.h.
Referenced by getPage(), and lookup().
Xapian::MSet MSetQlcTable::m_mset private
Definition at line 94 of file qlc.h.
Referenced by getPage(), lookup(), and size().
The documentation for this class was generated from the following files:
c_src/common/qlc.h
c_src/common/qlc.cpp