Xapian Erlang Binding: Terms Class Reference
Terms Class Reference
#include <termiter_doc_gen.h>
Public Member Functions
Terms (Xapian::Document &doc)
Xapian::TermIterator begin ()
Xapian::TermIterator end ()
Xapian::termcount size ()
Public Member Functions inherited from Iterator
virtual ~Iterator ()
virtual bool empty ()
Private Attributes
Xapian::Document m_doc
Additional Inherited Members
Static Public Member Functions inherited from Iterator
static Iterator * create (ParamDecoder &params, Xapian::ValueCountMatchSpy &spy)
static Iterator * create (Xapian::Document &doc)
static Iterator * create (ParamDecoder &params, Xapian::QueryParser &qp)
static Iterator * create (ParamDecoder &params, Xapian::Database &db)
Detailed Description
Generate TermIterator from Xapian::Document.
Definition at line 13 of file termiter_doc_gen.h.
Constructor & Destructor Documentation
Terms::Terms (Xapian::Document & doc) inline
Definition at line 18 of file termiter_doc_gen.h.
Member Function Documentation
Xapian::TermIterator Terms::begin () inline virtual
Implements Iterator.
Definition at line 21 of file termiter_doc_gen.h.
References m_doc.
Referenced by size().
Xapian::TermIterator Terms::end () inline virtual
Implements Iterator.
Definition at line 26 of file termiter_doc_gen.h.
References m_doc.
Referenced by size().
Xapian::termcount Terms::size () inline virtual
If size() is unknown, return 0. To check size is really 0, use empty().
Reimplemented from Iterator.
Definition at line 31 of file termiter_doc_gen.h.
References begin(), and end().
Member Data Documentation
Xapian::Document Terms::m_doc private
Definition at line 15 of file termiter_doc_gen.h.
Referenced by begin(), and end().
The documentation for this class was generated from the following file:
c_src/common/termiter_gen/termiter_doc_gen.h