Xapian Erlang Binding: Register Class Reference
Register Class Reference
#include <register.h>
Public Member Functions
Register ()
Element get (Counter num)
Counter put (Element)
void remove (Counter num)
void removeAny (Counter num)
~Register ()
void clear ()
Private Types
typedef uint32_t Counter
typedef HASH_MAP< Counter,
Element, HASH_TPL< uint32_t > > Hash
Private Attributes
Counter m_counter
Hash m_elements
Detailed Description
Definition at line 30 of file register.h.
Member Typedef Documentation
typedef uint32_t Register::Counter private
Definition at line 32 of file register.h.
typedef HASH_MAP< Counter, Element, HASH_TPL<uint32_t> > Register::Hash private
It is the mapping from id (of the type Counter) to the reference on the object.
Id will be generated automatically.
Definition at line 40 of file register.h.
Constructor & Destructor Documentation
XAPIAN_RESOURCE_NS_BEGIN Register::Register ()
Definition at line 7 of file register.cpp.
References m_counter, and m_elements.
Register::~Register ()
Definition at line 63 of file register.cpp.
References clear().
Member Function Documentation
void Register::clear ()
This method is called from m_stores.clear, that is called from driver.clear. It is called for all ObjectRegisters twice: the first tile, it is called while all other registers alive (directly), the second time, when they are alive partically (from ~ObjectRegister).
Definition at line 77 of file register.cpp.
References m_elements.
Referenced by ~Register().
Element Register::get (Register::Counter num)
Definition at line 26 of file register.cpp.
References m_elements.
Referenced by Factory::extract().
Register::Counter Register::put (Element elem)
Definition at line 16 of file register.cpp.
References m_counter, and m_elements.
Referenced by Factory::save().
void Register::remove (Register::Counter num)
Definition at line 39 of file register.cpp.
References m_elements.
Referenced by Factory::release().
void Register::removeAny (Register::Counter num)
Definition at line 53 of file register.cpp.
References m_elements.
Referenced by Factory::multiRelease().
Member Data Documentation
Counter Register::m_counter private
Definition at line 44 of file register.h.
Referenced by put(), and Register().
Hash Register::m_elements private
Definition at line 47 of file register.h.
Referenced by clear(), get(), put(), Register(), remove(), and removeAny().
The documentation for this class was generated from the following files:
c_src/common/resource/register.h
c_src/common/resource/register.cpp