Xapian Erlang Binding: ObjectBaseRegister Class Reference
ObjectBaseRegister Class Reference
#include <object_register.h>
Public Member Functions
virtual ~ObjectBaseRegister ()
virtual void remove (Counter)=0
virtual void * getVoidPointer (Counter)=0
virtual Counter putVoidPointer (void *obj)=0
virtual void * replaceWithoutCleaning (uint32_t num, void *new_obj)=0
Protected Types
typedef uint32_t Counter
Detailed Description
Definition at line 16 of file object_register.h.
Member Typedef Documentation
typedef uint32_t ObjectBaseRegister::Counter protected
Definition at line 19 of file object_register.h.
Constructor & Destructor Documentation
virtual ObjectBaseRegister::~ObjectBaseRegister () inline virtual
Definition at line 22 of file object_register.h.
Member Function Documentation
virtual void* ObjectBaseRegister::getVoidPointer (Counter) pure virtual
Implemented in ObjectRegister< Child >, ObjectRegister< const Xapian::DateValueRangeProcessor >, ObjectRegister< UserResource >, ObjectRegister< SpyController >, ObjectRegister< Xapian::MSet >, ObjectRegister< Xapian::KeyMaker >, ObjectRegister< Xapian::Enquire >, ObjectRegister< const Xapian::ExpandDecider >, ObjectRegister< const Xapian::Stem >, ObjectRegister< QlcTable >, ObjectRegister< const Xapian::MatchDecider >, ObjectRegister< const Xapian::Query >, ObjectRegister< const Xapian::Weight >, and ObjectRegister< Xapian::Document >.
Referenced by ResourceManager::get().
virtual Counter ObjectBaseRegister::putVoidPointer (void * obj) pure virtual
Implemented in ObjectRegister< Child >, ObjectRegister< const Xapian::DateValueRangeProcessor >, ObjectRegister< UserResource >, ObjectRegister< SpyController >, ObjectRegister< Xapian::MSet >, ObjectRegister< Xapian::KeyMaker >, ObjectRegister< Xapian::Enquire >, ObjectRegister< const Xapian::ExpandDecider >, ObjectRegister< const Xapian::Stem >, ObjectRegister< QlcTable >, ObjectRegister< const Xapian::MatchDecider >, ObjectRegister< const Xapian::Query >, ObjectRegister< const Xapian::Weight >, and ObjectRegister< Xapian::Document >.
Referenced by ResourceManager::createAndRegister().
virtual void ObjectBaseRegister::remove (Counter) pure virtual
Implemented in ObjectRegister< Child >, ObjectRegister< const Xapian::DateValueRangeProcessor >, ObjectRegister< UserResource >, ObjectRegister< SpyController >, ObjectRegister< Xapian::MSet >, ObjectRegister< Xapian::KeyMaker >, ObjectRegister< Xapian::Enquire >, ObjectRegister< const Xapian::ExpandDecider >, ObjectRegister< const Xapian::Stem >, ObjectRegister< QlcTable >, ObjectRegister< const Xapian::MatchDecider >, ObjectRegister< const Xapian::Query >, ObjectRegister< const Xapian::Weight >, and ObjectRegister< Xapian::Document >.
Referenced by Driver::releaseResource().
virtual void* ObjectBaseRegister::replaceWithoutCleaning (uint32_t num, void * new_obj) pure virtual
Implemented in ObjectRegister< Child >, ObjectRegister< const Xapian::DateValueRangeProcessor >, ObjectRegister< UserResource >, ObjectRegister< SpyController >, ObjectRegister< Xapian::MSet >, ObjectRegister< Xapian::KeyMaker >, ObjectRegister< Xapian::Enquire >, ObjectRegister< const Xapian::ExpandDecider >, ObjectRegister< const Xapian::Stem >, ObjectRegister< QlcTable >, ObjectRegister< const Xapian::MatchDecider >, ObjectRegister< const Xapian::Query >, ObjectRegister< const Xapian::Weight >, and ObjectRegister< Xapian::Document >.
The documentation for this class was generated from the following file:
c_src/object_register.h