Xapian Erlang Binding: HellTermPosition Class Reference
HellTermPosition Class Reference
Public Member Functions
HellTermPosition (Xapian::Document &doc, const std::string &tname)
void dec_wdf (const Xapian::termcount wdf)
void inc_wdf (const Xapian::termcount wdf)
void set_wdf (const Xapian::termcount wdf)
~HellTermPosition ()
Private Attributes
bool m_is_exist
Xapian::Document & m_doc
const std::string & m_tname
Static Private Attributes
static const Xapian::termpos HELL_POS = 666
Detailed Description
Tiny dirty class
Definition at line 1567 of file xapian_core.cpp.
Constructor & Destructor Documentation
HellTermPosition::HellTermPosition (Xapian::Document & doc, const std::string & tname) inline
Definition at line 1575 of file xapian_core.cpp.
References HELL_POS, Driver::isPostingExist(), Driver::isTermExist(), and m_is_exist.
HellTermPosition::~HellTermPosition () inline
Definition at line 1611 of file xapian_core.cpp.
References HELL_POS, m_doc, m_is_exist, and m_tname.
Member Function Documentation
void HellTermPosition::dec_wdf (const Xapian::termcount wdf) inline
Definition at line 1587 of file xapian_core.cpp.
References HELL_POS, m_doc, and m_tname.
Referenced by set_wdf(), and Driver::tryDecreaseWDF().
void HellTermPosition::inc_wdf (const Xapian::termcount wdf) inline
Definition at line 1594 of file xapian_core.cpp.
References m_doc, and m_tname.
Referenced by set_wdf().
void HellTermPosition::set_wdf (const Xapian::termcount wdf) inline
Definition at line 1600 of file xapian_core.cpp.
References dec_wdf(), Driver::getTermFrequency(), inc_wdf(), m_doc, and m_tname.
Referenced by Driver::trySetWDF().
Member Data Documentation
const Xapian::termpos HellTermPosition::HELL_POS = 666 static private
Definition at line 1569 of file xapian_core.cpp.
Referenced by dec_wdf(), HellTermPosition(), and ~HellTermPosition().
Xapian::Document& HellTermPosition::m_doc private
Definition at line 1571 of file xapian_core.cpp.
Referenced by dec_wdf(), inc_wdf(), set_wdf(), and ~HellTermPosition().
bool HellTermPosition::m_is_exist private
Definition at line 1570 of file xapian_core.cpp.
Referenced by HellTermPosition(), and ~HellTermPosition().
const std::string& HellTermPosition::m_tname private
Definition at line 1572 of file xapian_core.cpp.
Referenced by dec_wdf(), inc_wdf(), set_wdf(), and ~HellTermPosition().
The documentation for this class was generated from the following file:
c_src/xapian_core.cpp