Xapian Erlang Binding: WdfManipulation Class Reference
WdfManipulation Class Reference
#include <wdf_manipulation.h>
Public Member Functions
WdfManipulation (Xapian::Document &doc, const std::string &tname)
void dec_wdf (const Xapian::termcount wdf)
void inc_wdf (const Xapian::termcount wdf)
void set_wdf (const Xapian::termcount wdf)
~WdfManipulation ()
Private Attributes
bool m_is_exist
Xapian::Document & m_doc
const std::string & m_tname
Static Private Attributes
static const Xapian::termpos POS = 666
Detailed Description
Set, decrease, increase WDF of the document term. It is a tiny dirty class.
Because Xapian does not allow set the WDF of the term directly, we use this class.
For manipulations, we add the term position (posting), then remove it.
NewWDF = CurrentWDF + IncWDF - DecWDF;
The combination of IncWDF and DecWDF values produces the required WDF NewWDF: add_posting(term, pos, IncWDF); remove_posting(term, pos, DecWDF);
Definition at line 23 of file wdf_manipulation.h.
Constructor & Destructor Documentation
WdfManipulation::WdfManipulation (Xapian::Document & doc, const std::string & tname) inline
Definition at line 35 of file wdf_manipulation.h.
References Helpers::isPostingExist(), Helpers::isTermExist(), m_is_exist, and POS.
WdfManipulation::~WdfManipulation () inline
Definition at line 71 of file wdf_manipulation.h.
References m_doc, m_is_exist, m_tname, and POS.
Member Function Documentation
void WdfManipulation::dec_wdf (const Xapian::termcount wdf) inline
Definition at line 47 of file wdf_manipulation.h.
References m_doc, m_tname, and POS.
Referenced by set_wdf(), and Helpers::tryDecreaseWDF().
void WdfManipulation::inc_wdf (const Xapian::termcount wdf) inline
Definition at line 54 of file wdf_manipulation.h.
References m_doc, and m_tname.
Referenced by set_wdf().
void WdfManipulation::set_wdf (const Xapian::termcount wdf) inline
Definition at line 60 of file wdf_manipulation.h.
References dec_wdf(), Helpers::getTermFrequency(), inc_wdf(), m_doc, and m_tname.
Referenced by Helpers::trySetWDF().
Member Data Documentation
Xapian::Document& WdfManipulation::m_doc private
Definition at line 31 of file wdf_manipulation.h.
Referenced by dec_wdf(), inc_wdf(), set_wdf(), and ~WdfManipulation().
bool WdfManipulation::m_is_exist private
Definition at line 30 of file wdf_manipulation.h.
Referenced by WdfManipulation(), and ~WdfManipulation().
const std::string& WdfManipulation::m_tname private
Definition at line 32 of file wdf_manipulation.h.
Referenced by dec_wdf(), inc_wdf(), set_wdf(), and ~WdfManipulation().
const Xapian::termpos WdfManipulation::POS = 666 static private
The term position, used for manipulation. It can or cannot exist.
Definition at line 29 of file wdf_manipulation.h.
Referenced by dec_wdf(), WdfManipulation(), and ~WdfManipulation().
The documentation for this class was generated from the following file:
c_src/common/wdf_manipulation.h