Xapian Erlang Binding: ParamDecoder Class Reference
ParamDecoder Class Reference
#include <param_decoder.h>
Public Member Functions
ParamDecoder (char *buf, size_t len)
char * move (const size_t size)
char * currentPosition ()
Retrieves a variable from the buffer and moves the pointer on the next variable.
operator bool ()
operator int8_t ()
operator int32_t ()
operator uint8_t ()
operator uint16_t ()
operator uint32_t ()
operator double ()
operator const std::string ()
operator const Xapian::Stem ()
Private Attributes
char * m_buf
size_t m_len
Detailed Description
Decoder of the parameters from erlang's calls
Definition at line 19 of file param_decoder.h.
Constructor & Destructor Documentation
XAPIAN_ERLANG_NS_BEGIN ParamDecoder::ParamDecoder (char * buf, size_t len)
Constructor
Definition at line 20 of file param_decoder.cpp.
Member Function Documentation
char * ParamDecoder::currentPosition ()
Return a pointer on the current pointer position.
Definition at line 97 of file param_decoder.cpp.
References m_buf.
Referenced by Driver::applyDocumentSchema(), Driver::retrieveDocumentSchema(), and Driver::retrieveTermSchema().
char * ParamDecoder::move (const size_t size)
Skip the pointer on size_t bytes.
Definition at line 26 of file param_decoder.cpp.
References m_buf, and m_len.
ParamDecoder::operator bool ()
Definition at line 61 of file param_decoder.cpp.
References READ_TYPE.
ParamDecoder::operator const std::string ()
Decodes <<StringLen:32/native-signed-integer, StringBin/binary>>.
Definition at line 39 of file param_decoder.cpp.
References READ_TYPE.
ParamDecoder::operator const Xapian::Stem ()
Definition at line 91 of file param_decoder.cpp.
ParamDecoder::operator double ()
Definition at line 87 of file param_decoder.cpp.
References READ_TYPE.
ParamDecoder::operator int32_t ()
Decodes <<Num:32/native-signed-integer>>.
Definition at line 68 of file param_decoder.cpp.
References READ_TYPE.
ParamDecoder::operator int8_t ()
Decodes <<Int8t:8/native-signed-integer>>.
Definition at line 50 of file param_decoder.cpp.
References READ_TYPE.
ParamDecoder::operator uint16_t ()
Decodes <<Num:16/native-unsigned-integer>>.
Definition at line 83 of file param_decoder.cpp.
References READ_TYPE.
ParamDecoder::operator uint32_t ()
Decodes <<Num:32/native-unsigned-integer>>. Results are Xapian::valueno or Xapian::termcount.
Definition at line 76 of file param_decoder.cpp.
References READ_TYPE.
ParamDecoder::operator uint8_t ()
Decodes <<Int8t:8/native-unsigned-integer>>.
Definition at line 57 of file param_decoder.cpp.
References READ_TYPE.
Member Data Documentation
char* ParamDecoder::m_buf private
A current position of the pointer. Every move forward will increase this variable.
Definition at line 25 of file param_decoder.h.
Referenced by currentPosition(), and move().
size_t ParamDecoder::m_len private
A length in bytes of the remained buffer. Every move forward will decrease this variable.
Definition at line 31 of file param_decoder.h.
Referenced by move().
The documentation for this class was generated from the following files:
c_src/common/param_decoder.h
c_src/common/param_decoder.cpp