Xapian Erlang Binding: Element Class Reference
Element Class Reference
#include <element.h>
Public Member Functions
Element (Controller::Base &controller)
Element (Controller::Base *p_controller)
Element & operator= (const Element &source)
Assignment operator.
Element ()
Element (const Element &src)
Copy is allowed.
~Element ()
Controller::Base & get ()
void attach (Element &child)
void attachContext (Element &context)
operator Xapian::MSet & ()
operator Xapian::KeyMaker & ()
operator Xapian::Enquire & ()
operator QlcTable & ()
operator Xapian::Weight & ()
operator Xapian::Query & ()
operator Xapian::MatchDecider & ()
operator Xapian::ExpandDecider & ()
operator Xapian::ValueRangeProcessor & ()
operator Xapian::QueryParser & ()
operator Xapian::Stopper & ()
operator Xapian::Stem & ()
operator Xapian::ValueCountMatchSpy & ()
operator Xapian::MatchSpy & ()
operator Xapian::Document & ()
operator Extension::ValueCountMatchSpy & ()
void finalize ()
bool is_finalized ()
Static Public Member Functions
static Element wrap (Xapian::Weight *p_weight)
static Element wrap (Xapian::ValueRangeProcessor *p_proc)
static Element wrap (Xapian::KeyMaker *p_key_maker)
static Element wrap (Xapian::Enquire *p_enquire)
static Element wrap (Xapian::QueryParser *p_query_parser)
static Element wrap (Xapian::Document *p_document)
static Element wrap (Xapian::Query *p_query)
static Element wrap (Xapian::MSet *p_mset)
static Element wrap (Xapian::Stopper *p_stopper)
static Element wrap (QlcTable *p_table)
static Element wrap (uint32_t slot, Xapian::ValueCountMatchSpy *p_spy)
static Element createContext ()
Private Attributes
Controller::Base * mp_controller
Detailed Description
Definition at line 42 of file element.h.
Constructor & Destructor Documentation
XAPIAN_RESOURCE_NS_BEGIN Element::Element (Controller::Base & controller)
Definition at line 22 of file element.cpp.
References mp_controller.
Element::Element (Controller::Base * p_controller)
Definition at line 29 of file element.cpp.
References mp_controller.
Element::Element () inline
Definition at line 52 of file element.h.
Referenced by createContext(), and wrap().
Element::Element (const Element & src)
Copy is allowed.
Copy constructor.
Definition at line 38 of file element.cpp.
References mp_controller.
Element::~Element ()
Definition at line 65 of file element.cpp.
References mp_controller.
Member Function Documentation
void Element::attach (Element & child)
Use this object as a parent of the child object. Attached (child) objects cannot be used as a parent again.
Definition at line 74 of file element.cpp.
References mp_controller.
Referenced by Factory::extract().
void Element::attachContext (Element & context)
Attach children of the context.
If the context has no children, then do nothing.
Definition at line 82 of file element.cpp.
References mp_controller.
Element Element::createContext () static
Create a new context. Context is a object, that's goal is aggregating other Elements.
Definition at line 167 of file element.cpp.
References Element().
void Element::finalize ()
Definition at line 154 of file element.cpp.
References mp_controller.
Controller::Base& Element::get () inline
Definition at line 58 of file element.h.
References mp_controller.
Referenced by Base::attach(), and Base::attachContext().
bool Element::is_finalized ()
Definition at line 159 of file element.cpp.
References mp_controller.
Element::operator Extension::ValueCountMatchSpy & ()
Definition at line 149 of file element.cpp.
Element::operator QlcTable & ()
Definition at line 101 of file element.cpp.
Element::operator Xapian::Document & ()
Definition at line 145 of file element.cpp.
Element::operator Xapian::Enquire & ()
Definition at line 97 of file element.cpp.
Element::operator Xapian::ExpandDecider & ()
Definition at line 117 of file element.cpp.
Element::operator Xapian::KeyMaker & ()
Definition at line 93 of file element.cpp.
Element::operator Xapian::MatchDecider & ()
Definition at line 113 of file element.cpp.
Element::operator Xapian::MatchSpy & ()
Definition at line 141 of file element.cpp.
Element::operator Xapian::MSet & ()
Definition at line 89 of file element.cpp.
Element::operator Xapian::Query & ()
Definition at line 109 of file element.cpp.
Element::operator Xapian::QueryParser & ()
Definition at line 125 of file element.cpp.
Element::operator Xapian::Stem & ()
Definition at line 133 of file element.cpp.
Element::operator Xapian::Stopper & ()
Definition at line 129 of file element.cpp.
Element::operator Xapian::ValueCountMatchSpy & ()
Definition at line 137 of file element.cpp.
Element::operator Xapian::ValueRangeProcessor & ()
Definition at line 121 of file element.cpp.
Element::operator Xapian::Weight & ()
Definition at line 105 of file element.cpp.
Element & Element::operator= (const Element & source)
Assignment operator.
Definition at line 48 of file element.cpp.
References mp_controller.
Element Element::wrap (Xapian::Weight * p_weight) static
Definition at line 174 of file element.cpp.
References Element().
Referenced by createBM25Weight(), createBoolWeight(), createDateValueRangeProcessor3(), createDateValueRangeProcessor5(), createMultiValueKeyMaker(), createNumberValueRangeProcessor1(), createNumberValueRangeProcessor3(), createSimpleStopper(), createStringValueRangeProcessor1(), createStringValueRangeProcessor3(), createTradWeight(), and createValueCountMatchSpy().
Element Element::wrap (Xapian::ValueRangeProcessor * p_proc) static
Definition at line 188 of file element.cpp.
References Element().
Element Element::wrap (Xapian::KeyMaker * p_key_maker) static
Definition at line 195 of file element.cpp.
References Element().
Element Element::wrap (Xapian::Enquire * p_enquire) static
Definition at line 216 of file element.cpp.
References Element().
Element Element::wrap (Xapian::QueryParser * p_query_parser) static
Definition at line 223 of file element.cpp.
References Element().
Element Element::wrap (Xapian::Document * p_document) static
Definition at line 237 of file element.cpp.
References Element().
Element Element::wrap (Xapian::Query * p_query) static
Definition at line 230 of file element.cpp.
References Element().
Element Element::wrap (Xapian::MSet * p_mset) static
Definition at line 202 of file element.cpp.
References Element().
Element Element::wrap (Xapian::Stopper * p_stopper) static
Definition at line 244 of file element.cpp.
References Element().
Element Element::wrap (QlcTable * p_table) static
Definition at line 209 of file element.cpp.
References Element().
Element Element::wrap (uint32_t slot, Xapian::ValueCountMatchSpy * p_spy) static
Definition at line 181 of file element.cpp.
References Element().
Member Data Documentation
Controller::Base* Element::mp_controller private
Definition at line 44 of file element.h.
Referenced by attach(), attachContext(), Element(), finalize(), get(), is_finalized(), operator=(), and ~Element().
The documentation for this class was generated from the following files:
c_src/common/resource/element.h
c_src/common/resource/element.cpp