Xapian Erlang Binding: XapianErlangDriver Class Reference
XapianErlangDriver Class Reference
#include <xapian_core.h>
Public Types
enum command {
OPEN = 0, LAST_DOC_ID = 1, ADD_DOCUMENT = 2, TEST = 3,
GET_DOCUMENT_BY_ID = 4, START_TRANSACTION = 5, CANCEL_TRANSACTION = 6, COMMIT_TRANSACTION = 7,
QUERY_PAGE = 8, SET_DEFAULT_STEMMER = 9, SET_DEFAULT_PREFIXES = 10, ENQUIRE = 11,
RELEASE_RESOURCE = 12, MATCH_SET = 13, QLC_INIT = 14, QLC_NEXT_PORTION = 15,
QLC_LOOKUP = 16, GET_RESOURCE_INFO = 17, CREATE_RESOURCE = 18, MSET_INFO = 19,
DB_INFO = 20, DELETE_DOCUMENT = 21, REPLACE_DOCUMENT = 22, SET_METADATA = 23,
UPDATE_DOCUMENT = 24, UPDATE_OR_CREATE_DOCUMENT = 25, DOCUMENT = 26
}
enum errorCode { SUCCESS = 0, ERROR = 1 }
enum uniqueIdType { UNIQUE_DOCID = 1, UNIQUE_TERM = 2 }
enum openMode {
READ_OPEN = 0, WRITE_CREATE_OR_OPEN = 1, WRITE_CREATE = 2, WRITE_CREATE_OR_OVERWRITE = 3,
WRITE_OPEN = 4
}
enum fieldTypeIn {
STEMMER = 1, DATA = 2, DELTA = 3, TEXT = 4,
SET_POSTING = 15, ADD_POSTING = 25, UPDATE_POSTING = 35, REMOVE_POSTING = 45,
SET_TERM = 16, ADD_TERM = 26, UPDATE_TERM = 36, REMOVE_TERM = 46,
ADD_VALUE = 17, SET_VALUE = 27, UPDATE_VALUE = 37, REMOVE_VALUE = 47,
DEC_WDF = 101, SET_WDF = 111, REMOVE_VALUES = 103, REMOVE_TERMS = 104,
REMOVE_POSITIONS = 105, REMOVE_TERM_POSITIONS = 106, REMOVE_TERM_POSITIONS_SAVE = 116
}
enum fieldTypeOut {
GET_VALUE = 1, GET_DATA = 2, GET_DOCID = 3, GET_WEIGHT = 4,
GET_RANK = 5, GET_PERCENT = 6
}
enum testNumber { TEST_RESULT_ENCODER = 1, TEST_EXCEPTION = 2 }
enum queryType {
QUERY_GROUP = 1, QUERY_VALUE = 2, QUERY_VALUE_RANGE = 3, QUERY_TERM = 4,
QUERY_PARSER = 5
}
enum queryParserCommand {
QP_STEMMER = 1, QP_STEMMING_STRATEGY = 2, QP_MAX_WILDCARD_EXPANSION = 3, QP_DEFAULT_OP = 4,
QP_PARSER_TYPE = 5, QP_PREFIX = 6
}
enum queryParserType { QP_TYPE_DEFAULT = 0, QP_TYPE_EMPTY = 1 }
enum enquireCommand {
EC_STOP = 0, EC_QUERY = 1, EC_QUERY_LEN = 2, EC_ORDER = 3,
EC_DOCID_ORDER = 4, EC_WEIGHTING_SCHEME = 5, EC_CUTOFF = 6, EC_COLLAPSE_KEY = 7
}
see `xapian_enquire:encode'
enum enquireOrderTypes {
OT_KEY = 1, OT_VALUE = 2, OT_KEY_RELEVANCE = 3, OT_RELEVANCE_KEY = 4,
OT_RELEVANCE_VALUE = 5, OT_VALUE_RELEVANCE = 6
}
enum msetInfoParams {
MI_MATCHES_LOWER_BOUND = 1, MI_MATCHES_ESTIMATED = 2, MI_MATCHES_UPPER_BOUND = 3, MI_UNCOLLAPSED_MATCHES_LOWER_BOUND = 4,
MI_UNCOLLAPSED_MATCHES_ESTIMATED = 5, MI_UNCOLLAPSED_MATCHES_UPPER_BOUND = 6, MI_SIZE = 7, MI_GET_MAX_POSSIBLE = 8,
MI_GET_MAX_ATTAINED = 9, MI_TERM_WEIGHT = 10, MI_TERM_FREQ = 11
}
enum dbInfoParams {
DBI_HAS_POSITIONS = 1, DBI_DOCCOUNT = 2, DBI_LASTDOCID = 3, DBI_AVLENGTH = 4,
DBI_TERM_EXISTS = 5, DBI_TERM_FREQ = 6, DBI_COLLECTION_FREQ = 7, DBI_VALUE_FREQ = 8,
DBI_VALUE_LOWER_BOUND = 9, DBI_VALUE_UPPER_BOUND = 10, DBI_DOCLENGTH_LOWER_BOUND = 11, DBI_DOCLENGTH_UPPER_BOUND = 12,
DBI_WDF_UPPER_BOUND = 13, DBI_DOCLENGTH = 14, DBI_UUID = 15, DBI_METADATA = 16
}
enum termInfoFields {
TERM_VALUE = 1, TERM_WDF = 2, TERM_FREQ = 3, TERM_POSITIONS = 4,
TERM_POS_COUNT = 5
}
Public Member Functions
ResultEncoder * getResultEncoder ()
XapianErlangDriver (ResourceGenerator &)
~XapianErlangDriver ()
void setDefaultStemmer (const Xapian::Stem *stemmer)
size_t setDefaultStemmer (ParamDecoder &params)
size_t setDefaultPrefixes (ParamDecoder &params)
ObjectBaseRegister & getRegisterByType (uint8_t type)
size_t open (const std::string &dbpath, int8_t mode)
size_t getLastDocId ()
size_t addDocument (ParamDecoder &params)
size_t replaceDocument (ParamDecoder &params)
size_t updateDocument (ParamDecoder &params, bool create)
void deleteDocument (ParamDecoder &params)
void setMetadata (ParamDecoder &params)
size_t query (ParamDecoder &params)
size_t enquire (ParamDecoder &params)
Xapian::Document getDocument (ParamDecoder &params)
size_t document (ParamDecoder &params)
size_t releaseResource (ParamDecoder &params)
size_t matchSet (ParamDecoder &params)
size_t qlcInit (ParamDecoder &params)
size_t qlcNext (ParamDecoder &params)
size_t qlcLookup (ParamDecoder &params)
void retrieveDocument (ParamDecoder, Xapian::Document &, Xapian::MSetIterator *)
ParamDecoderController retrieveDocumentSchema (ParamDecoder &) const
void retrieveTerm (ParamDecoder params, const Xapian::TermIterator &iter)
ParamDecoderController retrieveTermSchema (ParamDecoder &params) const
void applyDocument (ParamDecoder &params, Xapian::Document &doc)
ParamDecoderController applyDocumentSchema (ParamDecoder &params) const
Xapian::Query buildQuery (ParamDecoder &params)
void fillEnquire (Xapian::Enquire &enquire, ParamDecoder &params)
void fillEnquireOrder (Xapian::Enquire &enquire, const uint8_t type, const uint32_t value, const bool reverse)
void assertWriteable () const
size_t startTransaction ()
size_t cancelTransaction ()
size_t commitTransaction ()
size_t getDocumentById (ParamDecoder &params)
size_t test (ParamDecoder &params)
size_t testResultEncoder (Xapian::docid from, Xapian::docid to)
size_t testException ()
size_t getResourceInfo ()
size_t createResource (ParamDecoder &params)
size_t msetInfo (ParamDecoder &params)
size_t databaseInfo (ParamDecoder &params)
Xapian::QueryParser readParser (ParamDecoder &params)
Xapian::QueryParser selectParser (ParamDecoder &params)
void addPrefix (Xapian::QueryParser &qp, ParamDecoder &params)
Static Public Member Functions
static int init ()
static void finish ()
static ErlDrvData start (ErlDrvPort port, char *)
static void stop (ErlDrvData drv_data)
static ErlDrvSSizeT control (ErlDrvData drv_data, unsigned int command, char *buf, ErlDrvSizeT len, char **rbuf, ErlDrvSizeT rlen)
static void retrieveTerm (ParamDecoder params, ResultEncoder &result, const Xapian::TermIterator &iter)
static unsigned idToParserFeature (uint8_t type)
static unsigned decodeParserFeatureFlags (ParamDecoder &params)
static
Xapian::QueryParser::stem_strategy readStemmingStrategy (ParamDecoder &params)
Static Public Attributes
static const unsigned PARSER_FEATURES []
static const uint8_t PARSER_FEATURE_COUNT = 13
static const uint8_t STEM_STRATEGY_COUNT = 3
static const
Xapian::QueryParser::stem_strategy STEM_STRATEGIES []
static const uint8_t DOCID_ORDER_TYPE_COUNT = 3
static const
Xapian::Enquire::docid_order DOCID_ORDER_TYPES []
Private Attributes
Xapian::Database * mp_db
Xapian::WritableDatabase * mp_wdb
const Xapian::Stem * mp_default_stemmer
ResultEncoder m_result
Xapian::QueryParser m_default_parser
Xapian::QueryParser m_empty_parser
ObjectRegister< Xapian::Document > m_document_store
ObjectRegister< Xapian::Enquire > m_enquire_store
ObjectRegister< Xapian::MSet > m_mset_store
ObjectRegister< QlcTable > m_qlc_store
ObjectRegister< const
Xapian::Weight > m_weight_store
ObjectRegister< Xapian::KeyMaker > m_key_maker_store
ObjectRegister< const
Xapian::Query > m_query_store
ObjectRegister< const
Xapian::MatchDecider > m_match_decider_store
ObjectRegister< const
Xapian::Stem > m_stem_store
ObjectRegister< const
Xapian::ExpandDecider > m_expand_decider_store
ObjectRegister< const
Xapian::DateValueRangeProcessor > m_date_value_range_processor_store
ObjectRegister< SpyController > m_match_spy_store
ResourceGenerator & m_generator
ResourceManager m_stores
Friends
class MSetQlcTable
class TermQlcTable
Private static helpers.
class HellTermPosition
TermIteratorGenerator * termGenerator (ParamDecoder &params, int8_t qlc_type, int8_t resource_type, uint32_t resource_num)
static Xapian::termcount getTermFrequency (Xapian::Document &doc, const std::string &tname)
static Xapian::termcount getExistedTermFrequency (Xapian::Document &doc, const std::string &tname)
static void tryRemoveValue (Xapian::Document &doc, Xapian::valueno slot_no, bool ignoreErrors)
static void tryRemoveTerm (Xapian::Document &doc, const std::string &tname, bool ignoreErrors)
static void tryRemovePosting (Xapian::Document &doc, const std::string &tname, Xapian::termpos tpos, Xapian::termcount wdf_inc, bool ignoreErrors)
static void tryDecreaseWDF (Xapian::Document &doc, const std::string &tname, Xapian::termcount wdf, bool ignoreErrors)
static void trySetWDF (Xapian::Document &doc, const std::string &tname, Xapian::termcount wdf, bool ignoreErrors)
static void tryClearTermPositions (Xapian::Document &doc, const std::string &tname, bool ignoreErrors)
static void clearTermPositions (Xapian::Document &doc, const std::string &tname)
static void clearTermPositions (Xapian::Document &doc)
static bool isValueExist (Xapian::Document &doc, Xapian::valueno slot_no)
static bool isTermExist (Xapian::Document &doc, const std::string &tname)
static bool isPostingExist (Xapian::Document &doc, const std::string &tname, Xapian::termpos term_pos)
static void handlePosting (uint8_t command, ParamDecoder &params, Xapian::Document &doc)
static void handleValue (uint8_t command, ParamDecoder &params, Xapian::Document &doc)
static void handleTerm (uint8_t command, ParamDecoder &params, Xapian::Document &doc)
static void qlcTermIteratorLookup (ParamDecoder &driver_params, const ParamDecoder &schema_params, ResultEncoder &result, Xapian::TermIterator iter, const Xapian::TermIterator end)
Detailed Description
Definition at line 29 of file xapian_core.h.
Member Enumeration Documentation
enum XapianErlangDriver::command
Enumerator:
OPEN
LAST_DOC_ID
ADD_DOCUMENT
TEST
GET_DOCUMENT_BY_ID
START_TRANSACTION
CANCEL_TRANSACTION
COMMIT_TRANSACTION
QUERY_PAGE
SET_DEFAULT_STEMMER
SET_DEFAULT_PREFIXES
ENQUIRE
RELEASE_RESOURCE
MATCH_SET
QLC_INIT
QLC_NEXT_PORTION
QLC_LOOKUP
GET_RESOURCE_INFO
CREATE_RESOURCE
MSET_INFO
DB_INFO
DELETE_DOCUMENT
REPLACE_DOCUMENT
SET_METADATA
UPDATE_DOCUMENT
UPDATE_OR_CREATE_DOCUMENT
DOCUMENT
Definition at line 70 of file xapian_core.h.
enum XapianErlangDriver::dbInfoParams
Enumerator:
DBI_HAS_POSITIONS
DBI_DOCCOUNT
DBI_LASTDOCID
DBI_AVLENGTH
DBI_TERM_EXISTS
DBI_TERM_FREQ
DBI_COLLECTION_FREQ
DBI_VALUE_FREQ
DBI_VALUE_LOWER_BOUND
DBI_VALUE_UPPER_BOUND
DBI_DOCLENGTH_LOWER_BOUND
DBI_DOCLENGTH_UPPER_BOUND
DBI_WDF_UPPER_BOUND
DBI_DOCLENGTH
DBI_UUID
DBI_METADATA
Definition at line 231 of file xapian_core.h.
enum XapianErlangDriver::enquireCommand
see `xapian_enquire:encode'
Enumerator:
EC_STOP
EC_QUERY
EC_QUERY_LEN
EC_ORDER
EC_DOCID_ORDER
EC_WEIGHTING_SCHEME
EC_CUTOFF
EC_COLLAPSE_KEY
Definition at line 197 of file xapian_core.h.
enum XapianErlangDriver::enquireOrderTypes
Enumerator:
OT_KEY
OT_VALUE
OT_KEY_RELEVANCE
OT_RELEVANCE_KEY
OT_RELEVANCE_VALUE
OT_VALUE_RELEVANCE
Definition at line 208 of file xapian_core.h.
enum XapianErlangDriver::errorCode
Enumerator:
SUCCESS
ERROR
Definition at line 103 of file xapian_core.h.
enum XapianErlangDriver::fieldTypeIn
Types of fields. Used in the applyDocument function.
Enumerator:
STEMMER
DATA
Set a stemmer.
DELTA
Set data.
TEXT
Add delta.
SET_POSTING
Set text.
ADD_POSTING
Add posting term.
UPDATE_POSTING
REMOVE_POSTING
SET_TERM
ADD_TERM
UPDATE_TERM
REMOVE_TERM
ADD_VALUE
SET_VALUE
UPDATE_VALUE
REMOVE_VALUE
DEC_WDF
SET_WDF
REMOVE_VALUES
REMOVE_TERMS
Clear all values.
REMOVE_POSITIONS
Clear all terms and postings.
REMOVE_TERM_POSITIONS
REMOVE_TERM_POSITIONS_SAVE
Definition at line 126 of file xapian_core.h.
enum XapianErlangDriver::fieldTypeOut
Types of the fields. Used in the retrieveDocument function.
Enumerator:
GET_VALUE
GET_DATA
GET_DOCID
GET_WEIGHT
GET_RANK
GET_PERCENT
Definition at line 158 of file xapian_core.h.
enum XapianErlangDriver::msetInfoParams
Enumerator:
MI_MATCHES_LOWER_BOUND
MI_MATCHES_ESTIMATED
MI_MATCHES_UPPER_BOUND
MI_UNCOLLAPSED_MATCHES_LOWER_BOUND
MI_UNCOLLAPSED_MATCHES_ESTIMATED
MI_UNCOLLAPSED_MATCHES_UPPER_BOUND
MI_SIZE
MI_GET_MAX_POSSIBLE
MI_GET_MAX_ATTAINED
MI_TERM_WEIGHT
MI_TERM_FREQ
Definition at line 217 of file xapian_core.h.
enum XapianErlangDriver::openMode
Enumerator:
READ_OPEN
WRITE_CREATE_OR_OPEN
WRITE_CREATE
WRITE_CREATE_OR_OVERWRITE
WRITE_OPEN
Definition at line 116 of file xapian_core.h.
enum XapianErlangDriver::queryParserCommand
Enumerator:
QP_STEMMER
QP_STEMMING_STRATEGY
QP_MAX_WILDCARD_EXPANSION
QP_DEFAULT_OP
QP_PARSER_TYPE
QP_PREFIX
Definition at line 182 of file xapian_core.h.
enum XapianErlangDriver::queryParserType
Enumerator:
QP_TYPE_DEFAULT
QP_TYPE_EMPTY
Definition at line 191 of file xapian_core.h.
enum XapianErlangDriver::queryType
Enumerator:
QUERY_GROUP
QUERY_VALUE
QUERY_VALUE_RANGE
QUERY_TERM
QUERY_PARSER
Definition at line 174 of file xapian_core.h.
enum XapianErlangDriver::termInfoFields
Enumerator:
TERM_VALUE
TERM_WDF
TERM_FREQ
TERM_POSITIONS
TERM_POS_COUNT
Definition at line 250 of file xapian_core.h.
enum XapianErlangDriver::testNumber
Numbers of tests. Used in the test function.
Enumerator:
TEST_RESULT_ENCODER
TEST_EXCEPTION
Definition at line 169 of file xapian_core.h.
enum XapianErlangDriver::uniqueIdType
Enumerator:
UNIQUE_DOCID
UNIQUE_TERM
Definition at line 109 of file xapian_core.h.
Constructor & Destructor Documentation
XapianErlangDriver::XapianErlangDriver (ResourceGenerator & generator)
A constructor.
Definition at line 156 of file xapian_core.cpp.
References ResourceManager::add(), ResourceType::DATE_VALUE_RANGE_PROCESSOR, ResourceType::DOCUMENT, ResourceType::ENQUIRE, ResourceType::EXPAND_DECIDER, ResourceType::KEY_MAKER, m_date_value_range_processor_store, m_document_store, m_enquire_store, m_expand_decider_store, m_key_maker_store, m_match_decider_store, m_match_spy_store, m_mset_store, m_qlc_store, m_query_store, m_stem_store, m_stores, m_weight_store, ResourceType::MATCH_DECIDER, ResourceType::MATCH_SPY, mp_db, mp_default_stemmer, mp_wdb, ResourceType::MSET, ResourceType::QLC_TABLE, ResourceType::QUERY, ResourceType::STEM, and ResourceType::WEIGHT.
Referenced by start().
XapianErlangDriver::~XapianErlangDriver ()
Definition at line 181 of file xapian_core.cpp.
References mp_db, and mp_default_stemmer.
Member Function Documentation
size_t XapianErlangDriver::addDocument (ParamDecoder & params)
Definition at line 242 of file xapian_core.cpp.
References applyDocument(), assertWriteable(), m_result, and mp_wdb.
Referenced by control().
void XapianErlangDriver::addPrefix (Xapian::QueryParser & qp, ParamDecoder & params)
Definition at line 770 of file xapian_core.cpp.
Referenced by readParser(), and setDefaultPrefixes().
void XapianErlangDriver::applyDocument (ParamDecoder & params, Xapian::Document & doc)
Read commands, encoded by `xapian_document:encode'. Used in update, replace, add document functions.
Definition at line 1240 of file xapian_core.cpp.
References ADD_POSTING, ADD_TERM, ADD_VALUE, clearTermPositions(), DATA, DEC_WDF, DELTA, handlePosting(), handleTerm(), handleValue(), mp_default_stemmer, REMOVE_POSITIONS, REMOVE_POSTING, REMOVE_TERM, REMOVE_TERM_POSITIONS, REMOVE_TERMS, REMOVE_VALUE, REMOVE_VALUES, SET_POSTING, SET_TERM, SET_VALUE, SET_WDF, STEMMER, termGenerator(), TEXT, tryClearTermPositions(), tryDecreaseWDF(), trySetWDF(), UPDATE_POSTING, UPDATE_TERM, and UPDATE_VALUE.
Referenced by addDocument(), replaceDocument(), and updateDocument().
ParamDecoderController XapianErlangDriver::applyDocumentSchema (ParamDecoder & params) const
Definition at line 1994 of file xapian_core.cpp.
References ADD_POSTING, ADD_TERM, ADD_VALUE, ParamDecoder::currentPosition(), DATA, DEC_WDF, DELTA, REMOVE_POSITIONS, REMOVE_POSTING, REMOVE_TERM, REMOVE_TERM_POSITIONS, REMOVE_TERMS, REMOVE_VALUE, REMOVE_VALUES, SET_POSTING, SET_TERM, SET_VALUE, SET_WDF, STEMMER, TEXT, UPDATE_POSTING, UPDATE_TERM, and UPDATE_VALUE.
Referenced by updateDocument().
void XapianErlangDriver::assertWriteable () const
Throws error if the database was opened only for reading.
Definition at line 653 of file xapian_core.cpp.
References mp_wdb.
Referenced by addDocument(), cancelTransaction(), commitTransaction(), deleteDocument(), replaceDocument(), setMetadata(), startTransaction(), and updateDocument().
Xapian::Query XapianErlangDriver::buildQuery (ParamDecoder & params)
Definition at line 785 of file xapian_core.cpp.
References decodeParserFeatureFlags(), QUERY_GROUP, QUERY_PARSER, QUERY_TERM, QUERY_VALUE, QUERY_VALUE_RANGE, and readParser().
Referenced by fillEnquire(), and query().
size_t XapianErlangDriver::cancelTransaction ()
Definition at line 671 of file xapian_core.cpp.
References assertWriteable(), m_result, and mp_wdb.
Referenced by control().
void XapianErlangDriver::clearTermPositions (Xapian::Document & doc, const std::string & tname) [static, private]
Definition at line 1705 of file xapian_core.cpp.
References getExistedTermFrequency().
Referenced by applyDocument(), and tryClearTermPositions().
void XapianErlangDriver::clearTermPositions (Xapian::Document & doc) [static, private]
Definition at line 1717 of file xapian_core.cpp.
size_t XapianErlangDriver::commitTransaction ()
Definition at line 681 of file xapian_core.cpp.
References assertWriteable(), m_result, and mp_wdb.
Referenced by control().
ErlDrvSSizeT XapianErlangDriver::control (ErlDrvData drv_data, unsigned int command, char * buf, ErlDrvSizeT len, char ** rbuf, ErlDrvSizeT rlen) [static]
Definition at line 1060 of file xapian_core.cpp.
References ADD_DOCUMENT, addDocument(), CANCEL_TRANSACTION, cancelTransaction(), ResultEncoder::clear(), COMMIT_TRANSACTION, commitTransaction(), CREATE_RESOURCE, createResource(), databaseInfo(), DB_INFO, DELETE_DOCUMENT, deleteDocument(), DOCUMENT, document(), ENQUIRE, enquire(), ERROR, GET_DOCUMENT_BY_ID, GET_RESOURCE_INFO, DriverRuntimeError::get_type(), getDocumentById(), getLastDocId(), getResourceInfo(), getResultEncoder(), LAST_DOC_ID, MATCH_SET, matchSet(), MSET_INFO, msetInfo(), OPEN, open(), QLC_INIT, QLC_LOOKUP, QLC_NEXT_PORTION, qlcInit(), qlcLookup(), qlcNext(), query(), QUERY_PAGE, RELEASE_RESOURCE, releaseResource(), REPLACE_DOCUMENT, replaceDocument(), SET_DEFAULT_PREFIXES, SET_DEFAULT_STEMMER, SET_METADATA, ResultEncoder::setBuffer(), setDefaultPrefixes(), setDefaultStemmer(), setMetadata(), START_TRANSACTION, startTransaction(), SUCCESS, TEST, test(), UPDATE_DOCUMENT, UPDATE_OR_CREATE_DOCUMENT, and updateDocument().
size_t XapianErlangDriver::createResource (ParamDecoder & params)
Create a resource object using an user function.
Definition at line 2152 of file xapian_core.cpp.
References ResourceManager::createAndRegister(), m_result, and m_stores.
Referenced by control().
size_t XapianErlangDriver::databaseInfo (ParamDecoder & params)
Definition at line 2230 of file xapian_core.cpp.
References DBI_AVLENGTH, DBI_COLLECTION_FREQ, DBI_DOCCOUNT, DBI_DOCLENGTH, DBI_DOCLENGTH_LOWER_BOUND, DBI_DOCLENGTH_UPPER_BOUND, DBI_HAS_POSITIONS, DBI_LASTDOCID, DBI_METADATA, DBI_TERM_EXISTS, DBI_TERM_FREQ, DBI_UUID, DBI_VALUE_FREQ, DBI_VALUE_LOWER_BOUND, DBI_VALUE_UPPER_BOUND, DBI_WDF_UPPER_BOUND, m_result, and mp_db.
Referenced by control().
unsigned XapianErlangDriver::decodeParserFeatureFlags (ParamDecoder & params) [static]
Definition at line 748 of file xapian_core.cpp.
References idToParserFeature().
Referenced by buildQuery().
void XapianErlangDriver::deleteDocument (ParamDecoder & params)
Definition at line 368 of file xapian_core.cpp.
References assertWriteable(), mp_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by control().
size_t XapianErlangDriver::document (ParamDecoder & params)
Return a resource
Definition at line 482 of file xapian_core.cpp.
References getDocument(), m_document_store, m_result, and ObjectRegister< Child >::put().
Referenced by control().
size_t XapianErlangDriver::enquire (ParamDecoder & params)
Return a resource.
Definition at line 424 of file xapian_core.cpp.
References fillEnquire(), m_enquire_store, m_result, mp_db, and ObjectRegister< Child >::put().
Referenced by control(), getDocument(), matchSet(), query(), and updateDocument().
void XapianErlangDriver::fillEnquire (Xapian::Enquire & enquire, ParamDecoder & params)
Definition at line 870 of file xapian_core.cpp.
References buildQuery(), DOCID_ORDER_TYPE_COUNT, DOCID_ORDER_TYPES, EC_COLLAPSE_KEY, EC_CUTOFF, EC_DOCID_ORDER, EC_ORDER, EC_QUERY, EC_QUERY_LEN, EC_WEIGHTING_SCHEME, fillEnquireOrder(), ObjectRegister< Child >::get(), m_weight_store, and query().
Referenced by enquire().
void XapianErlangDriver::fillEnquireOrder (Xapian::Enquire & enquire, const uint8_t type, const uint32_t value, const bool reverse)
Definition at line 945 of file xapian_core.cpp.
References OT_KEY, OT_KEY_RELEVANCE, OT_RELEVANCE_KEY, OT_RELEVANCE_VALUE, OT_VALUE, and OT_VALUE_RELEVANCE.
Referenced by fillEnquire().
void XapianErlangDriver::finish () [static]
The driver is unloaded. This is called only once.
Delete global variables
Definition at line 114 of file xapian_core.cpp.
References gp_generator.
Xapian::Document XapianErlangDriver::getDocument (ParamDecoder & params)
Definition at line 440 of file xapian_core.cpp.
References enquire(), mp_db, mp_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by document().
size_t XapianErlangDriver::getDocumentById (ParamDecoder & params)
Definition at line 691 of file xapian_core.cpp.
References m_result, mp_db, and retrieveDocument().
Referenced by control().
Xapian::termcount XapianErlangDriver::getExistedTermFrequency (Xapian::Document & doc, const std::string & tname) [static, private]
Definition at line 1517 of file xapian_core.cpp.
Referenced by clearTermPositions().
size_t XapianErlangDriver::getLastDocId ()
Definition at line 231 of file xapian_core.cpp.
References m_result, and mp_db.
Referenced by control().
ObjectBaseRegister & XapianErlangDriver::getRegisterByType (uint8_t type)
Definition at line 224 of file xapian_core.cpp.
References ResourceManager::get(), and m_stores.
Referenced by releaseResource().
size_t XapianErlangDriver::getResourceInfo ()
This function will be called inside xapian_drv:init
Definition at line 2128 of file xapian_core.cpp.
References ObjectRegister< Child >::getElements(), UserResource::getName(), ResourceGenerator::getRegister(), UserResource::getType(), m_generator, and m_result.
Referenced by control().
ResultEncoder * XapianErlangDriver::getResultEncoder ()
Definition at line 150 of file xapian_core.cpp.
References m_result.
Referenced by control().
Xapian::termcount XapianErlangDriver::getTermFrequency (Xapian::Document & doc, const std::string & tname) [static, private]
Definition at line 1498 of file xapian_core.cpp.
Referenced by handleTerm(), and HellTermPosition::set_wdf().
void XapianErlangDriver::handlePosting (uint8_t command, ParamDecoder & params, Xapian::Document & doc) [static, private]
Definition at line 1451 of file xapian_core.cpp.
References ADD_POSTING, isPostingExist(), REMOVE_POSTING, tryRemovePosting(), and UPDATE_POSTING.
Referenced by applyDocument().
void XapianErlangDriver::handleTerm (uint8_t command, ParamDecoder & params, Xapian::Document & doc) [static, private]
Definition at line 1358 of file xapian_core.cpp.
References ADD_TERM, getTermFrequency(), isTermExist(), REMOVE_TERM, tryRemoveTerm(), and UPDATE_TERM.
Referenced by applyDocument().
void XapianErlangDriver::handleValue (uint8_t command, ParamDecoder & params, Xapian::Document & doc) [static, private]
Definition at line 1405 of file xapian_core.cpp.
References ADD_VALUE, isValueExist(), REMOVE_VALUE, tryRemoveValue(), and UPDATE_VALUE.
Referenced by applyDocument().
unsigned XapianErlangDriver::idToParserFeature (uint8_t type) [static]
Definition at line 739 of file xapian_core.cpp.
References PARSER_FEATURE_COUNT, and PARSER_FEATURES.
Referenced by decodeParserFeatureFlags().
int XapianErlangDriver::init () [static]
The driver is loaded. This is called only once.
Create global variables
Definition at line 99 of file xapian_core.cpp.
References registerUserCallbacks().
bool XapianErlangDriver::isPostingExist (Xapian::Document & doc, const std::string & tname, Xapian::termpos term_pos) [static, private]
Definition at line 1768 of file xapian_core.cpp.
Referenced by handlePosting(), and HellTermPosition::HellTermPosition().
bool XapianErlangDriver::isTermExist (Xapian::Document & doc, const std::string & tname) [static, private]
Definition at line 1753 of file xapian_core.cpp.
Referenced by handleTerm(), and HellTermPosition::HellTermPosition().
bool XapianErlangDriver::isValueExist (Xapian::Document & doc, Xapian::valueno slot_no) [static, private]
Definition at line 1738 of file xapian_core.cpp.
Referenced by handleValue().
size_t XapianErlangDriver::matchSet (ParamDecoder & params)
Converts an enquire into a match set. Return a resource.
Definition at line 506 of file xapian_core.cpp.
References enquire(), SpyController::finalize(), ObjectRegister< Child >::get(), SpyController::getSpy(), SpyController::is_finalized(), m_enquire_store, m_match_spy_store, m_mset_store, m_result, mp_db, and ObjectRegister< Child >::put().
Referenced by control().
size_t XapianErlangDriver::msetInfo (ParamDecoder & params)
Definition at line 2161 of file xapian_core.cpp.
References ObjectRegister< Child >::get(), m_mset_store, m_result, MI_GET_MAX_ATTAINED, MI_GET_MAX_POSSIBLE, MI_MATCHES_ESTIMATED, MI_MATCHES_LOWER_BOUND, MI_MATCHES_UPPER_BOUND, MI_SIZE, MI_TERM_FREQ, MI_TERM_WEIGHT, MI_UNCOLLAPSED_MATCHES_ESTIMATED, MI_UNCOLLAPSED_MATCHES_LOWER_BOUND, and MI_UNCOLLAPSED_MATCHES_UPPER_BOUND.
Referenced by control().
size_t XapianErlangDriver::open (const std::string & dbpath, int8_t mode)
Definition at line 1193 of file xapian_core.cpp.
References m_default_parser, m_empty_parser, m_result, m_stores, mp_db, mp_wdb, READ_OPEN, ResourceManager::set_database(), WRITE_CREATE, WRITE_CREATE_OR_OPEN, WRITE_CREATE_OR_OVERWRITE, and WRITE_OPEN.
Referenced by control().
size_t XapianErlangDriver::qlcInit (ParamDecoder & params)
Definition at line 551 of file xapian_core.cpp.
References ObjectRegister< Child >::get(), m_mset_store, m_qlc_store, m_result, QlcType::MSET, ResourceType::MSET, MSetQlcTable, MSetQlcTable::numOfObjects(), TermQlcTable::numOfObjects(), ObjectRegister< Child >::put(), retrieveDocumentSchema(), retrieveTermSchema(), QlcType::SPY_TERMS, termGenerator(), TermQlcTable, and QlcType::TERMS.
Referenced by control().
size_t XapianErlangDriver::qlcLookup (ParamDecoder & params)
Definition at line 642 of file xapian_core.cpp.
References ObjectRegister< Child >::get(), QlcTable::lookup(), m_qlc_store, and m_result.
Referenced by control().
size_t XapianErlangDriver::qlcNext (ParamDecoder & params)
Definition at line 629 of file xapian_core.cpp.
References ObjectRegister< Child >::get(), QlcTable::getPage(), m_qlc_store, and m_result.
Referenced by control().
void XapianErlangDriver::qlcTermIteratorLookup (ParamDecoder & driver_params, const ParamDecoder & schema_params, ResultEncoder & result, Xapian::TermIterator iter, const Xapian::TermIterator end) [static, private]
Allow to find and write terms by name.
Helper for TermQlcTable class. Use set order of elements.
Parameters:
driver_params Contains which keys (term names) to find. Ends with "".
schema_params Contains which fields to write.
result A buffer for writing.
iter First term for searching in.
end Last term for searching in.
Definition at line 2361 of file xapian_core.cpp.
References retrieveTerm(), and stop().
Referenced by TermQlcTable::lookup().
size_t XapianErlangDriver::query (ParamDecoder & params)
`query_page'
Definition at line 395 of file xapian_core.cpp.
References buildQuery(), enquire(), m_result, mp_db, and retrieveDocument().
Referenced by control(), and fillEnquire().
Xapian::QueryParser XapianErlangDriver::readParser (ParamDecoder & params)
Definition at line 998 of file xapian_core.cpp.
References addPrefix(), m_default_parser, QP_DEFAULT_OP, QP_MAX_WILDCARD_EXPANSION, QP_PARSER_TYPE, QP_PREFIX, QP_STEMMER, QP_STEMMING_STRATEGY, readStemmingStrategy(), and selectParser().
Referenced by buildQuery().
Xapian::QueryParser::stem_strategy XapianErlangDriver::readStemmingStrategy (ParamDecoder & params) [static]
Definition at line 760 of file xapian_core.cpp.
References STEM_STRATEGIES, and STEM_STRATEGY_COUNT.
Referenced by readParser().
size_t XapianErlangDriver::releaseResource (ParamDecoder & params)
Erase the stored object.
Definition at line 493 of file xapian_core.cpp.
References getRegisterByType(), m_result, and ObjectBaseRegister::remove().
Referenced by control().
size_t XapianErlangDriver::replaceDocument (ParamDecoder & params)
Definition at line 256 of file xapian_core.cpp.
References applyDocument(), assertWriteable(), m_result, mp_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by control().
void XapianErlangDriver::retrieveDocument (ParamDecoder params, Xapian::Document & doc, Xapian::MSetIterator * mset_iter)
Gets a copy of params.
`params' is a clone.
Definition at line 1799 of file xapian_core.cpp.
References GET_DATA, GET_DOCID, GET_PERCENT, GET_RANK, GET_VALUE, GET_WEIGHT, and m_result.
Referenced by getDocumentById(), MSetQlcTable::getPage(), MSetQlcTable::lookup(), and query().
ParamDecoderController XapianErlangDriver::retrieveDocumentSchema (ParamDecoder & params) const
Definition at line 1955 of file xapian_core.cpp.
References ParamDecoder::currentPosition(), GET_DATA, GET_DOCID, GET_PERCENT, GET_RANK, GET_VALUE, and GET_WEIGHT.
Referenced by qlcInit().
void XapianErlangDriver::retrieveTerm (ParamDecoder params, const Xapian::TermIterator & iter)
Definition at line 1870 of file xapian_core.cpp.
References m_result.
Referenced by TermQlcTable::getPageKnownSize(), TermQlcTable::getPageUnknownSize(), and qlcTermIteratorLookup().
void XapianErlangDriver::retrieveTerm (ParamDecoder params, ResultEncoder & result, const Xapian::TermIterator & iter) [static]
Definition at line 1879 of file xapian_core.cpp.
References TERM_FREQ, TERM_POS_COUNT, TERM_POSITIONS, TERM_VALUE, and TERM_WDF.
ParamDecoderController XapianErlangDriver::retrieveTermSchema (ParamDecoder & params) const
Definition at line 1935 of file xapian_core.cpp.
References ParamDecoder::currentPosition().
Referenced by qlcInit().
Xapian::QueryParser XapianErlangDriver::selectParser (ParamDecoder & params)
Definition at line 980 of file xapian_core.cpp.
References m_default_parser, m_empty_parser, QP_TYPE_DEFAULT, and QP_TYPE_EMPTY.
Referenced by readParser().
size_t XapianErlangDriver::setDefaultPrefixes (ParamDecoder & params)
Definition at line 212 of file xapian_core.cpp.
References addPrefix(), m_default_parser, and m_result.
Referenced by control().
void XapianErlangDriver::setDefaultStemmer (const Xapian::Stem * stemmer)
Definition at line 192 of file xapian_core.cpp.
References m_default_parser, and mp_default_stemmer.
Referenced by control(), and setDefaultStemmer().
size_t XapianErlangDriver::setDefaultStemmer (ParamDecoder & params)
Definition at line 203 of file xapian_core.cpp.
References m_result, and setDefaultStemmer().
void XapianErlangDriver::setMetadata (ParamDecoder & params)
Definition at line 2338 of file xapian_core.cpp.
References assertWriteable(), and mp_wdb.
Referenced by control().
ErlDrvData XapianErlangDriver::start (ErlDrvPort port, char *) [static]
Here we do some initialization, start is called from `open_port'. The drv_data will be passed to control and stop. This is called multiple times.
Definition at line 124 of file xapian_core.cpp.
References XapianErlangDriver().
size_t XapianErlangDriver::startTransaction ()
Definition at line 661 of file xapian_core.cpp.
References assertWriteable(), m_result, and mp_wdb.
Referenced by control().
void XapianErlangDriver::stop (ErlDrvData drv_data) [static]
This is called multiple times.
Definition at line 138 of file xapian_core.cpp.
Referenced by qlcTermIteratorLookup().
TermIteratorGenerator * XapianErlangDriver::termGenerator (ParamDecoder & params, int8_t qlc_type, int8_t resource_type, uint32_t resource_num) [private]
Caller must delete returned value.
Definition at line 599 of file xapian_core.cpp.
References ResourceType::DOCUMENT, ObjectRegister< Child >::get(), SpyController::getIteratorGenerator(), m_document_store, m_match_spy_store, ResourceType::MATCH_SPY, QlcType::SPY_TERMS, and QlcType::TERMS.
Referenced by applyDocument(), and qlcInit().
size_t XapianErlangDriver::test (ParamDecoder & params)
Definition at line 701 of file xapian_core.cpp.
References TEST_EXCEPTION, TEST_RESULT_ENCODER, testException(), and testResultEncoder().
Referenced by control().
size_t XapianErlangDriver::testException ()
Definition at line 731 of file xapian_core.cpp.
Referenced by test().
size_t XapianErlangDriver::testResultEncoder (Xapian::docid from, Xapian::docid to)
Definition at line 722 of file xapian_core.cpp.
References m_result.
Referenced by test().
void XapianErlangDriver::tryClearTermPositions (Xapian::Document & doc, const std::string & tname, bool ignoreErrors) [static, private]
Definition at line 1689 of file xapian_core.cpp.
References clearTermPositions().
Referenced by applyDocument().
void XapianErlangDriver::tryDecreaseWDF (Xapian::Document & doc, const std::string & tname, Xapian::termcount wdf, bool ignoreErrors) [static, private]
Definition at line 1635 of file xapian_core.cpp.
References HellTermPosition::dec_wdf().
Referenced by applyDocument().
void XapianErlangDriver::tryRemovePosting (Xapian::Document & doc, const std::string & tname, Xapian::termpos tpos, Xapian::termcount wdf_inc, bool ignoreErrors) [static, private]
Definition at line 1563 of file xapian_core.cpp.
Referenced by handlePosting().
void XapianErlangDriver::tryRemoveTerm (Xapian::Document & doc, const std::string & tname, bool ignoreErrors) [static, private]
Definition at line 1550 of file xapian_core.cpp.
Referenced by handleTerm().
void XapianErlangDriver::tryRemoveValue (Xapian::Document & doc, Xapian::valueno slot_no, bool ignoreErrors) [static, private]
Definition at line 1537 of file xapian_core.cpp.
Referenced by handleValue().
void XapianErlangDriver::trySetWDF (Xapian::Document & doc, const std::string & tname, Xapian::termcount wdf, bool ignoreErrors) [static, private]
Definition at line 1662 of file xapian_core.cpp.
References HellTermPosition::set_wdf().
Referenced by applyDocument().
size_t XapianErlangDriver::updateDocument (ParamDecoder & params, bool create)
Definition at line 290 of file xapian_core.cpp.
References applyDocument(), applyDocumentSchema(), assertWriteable(), enquire(), m_result, mp_wdb, UNIQUE_DOCID, and UNIQUE_TERM.
Referenced by control().
Friends And Related Function Documentation
friend class HellTermPosition [friend]
Definition at line 528 of file xapian_core.h.
friend class MSetQlcTable [friend]
Definition at line 65 of file xapian_core.h.
Referenced by qlcInit().
friend class TermQlcTable [friend]
Definition at line 66 of file xapian_core.h.
Referenced by qlcInit().
Member Data Documentation
const uint8_t XapianErlangDriver::DOCID_ORDER_TYPE_COUNT = 3 [static]
Definition at line 271 of file xapian_core.h.
Referenced by fillEnquire().
const Xapian::Enquire::docid_order XapianErlangDriver::DOCID_ORDER_TYPES [static]
Initial value:
 {
     Xapian::Enquire::ASCENDING,
     Xapian::Enquire::DESCENDING,
     Xapian::Enquire::DONT_CARE
}
Definition at line 274 of file xapian_core.h.
Referenced by fillEnquire().
ObjectRegister<const Xapian::DateValueRangeProcessor> XapianErlangDriver::m_date_value_range_processor_store [private]
Definition at line 49 of file xapian_core.h.
Referenced by XapianErlangDriver().
Xapian::QueryParser XapianErlangDriver::m_default_parser [private]
Definition at line 36 of file xapian_core.h.
Referenced by open(), readParser(), selectParser(), setDefaultPrefixes(), and setDefaultStemmer().
ObjectRegister<Xapian::Document> XapianErlangDriver::m_document_store [private]
Definition at line 38 of file xapian_core.h.
Referenced by document(), termGenerator(), and XapianErlangDriver().
Xapian::QueryParser XapianErlangDriver::m_empty_parser [private]
Definition at line 37 of file xapian_core.h.
Referenced by open(), and selectParser().
ObjectRegister<Xapian::Enquire> XapianErlangDriver::m_enquire_store [private]
Definition at line 39 of file xapian_core.h.
Referenced by enquire(), matchSet(), and XapianErlangDriver().
ObjectRegister<const Xapian::ExpandDecider> XapianErlangDriver::m_expand_decider_store [private]
Definition at line 47 of file xapian_core.h.
Referenced by XapianErlangDriver().
ResourceGenerator& XapianErlangDriver::m_generator [private]
It is global. It knows how to create user customized resources.
Definition at line 56 of file xapian_core.h.
Referenced by getResourceInfo().
ObjectRegister<Xapian::KeyMaker> XapianErlangDriver::m_key_maker_store [private]
Definition at line 43 of file xapian_core.h.
Referenced by XapianErlangDriver().
ObjectRegister<const Xapian::MatchDecider> XapianErlangDriver::m_match_decider_store [private]
Definition at line 45 of file xapian_core.h.
Referenced by XapianErlangDriver().
ObjectRegister<SpyController> XapianErlangDriver::m_match_spy_store [private]
Definition at line 50 of file xapian_core.h.
Referenced by matchSet(), termGenerator(), and XapianErlangDriver().
ObjectRegister<Xapian::MSet> XapianErlangDriver::m_mset_store [private]
Definition at line 40 of file xapian_core.h.
Referenced by matchSet(), msetInfo(), qlcInit(), and XapianErlangDriver().
ObjectRegister<QlcTable> XapianErlangDriver::m_qlc_store [private]
Definition at line 41 of file xapian_core.h.
Referenced by qlcInit(), qlcLookup(), qlcNext(), and XapianErlangDriver().
ObjectRegister<const Xapian::Query> XapianErlangDriver::m_query_store [private]
Definition at line 44 of file xapian_core.h.
Referenced by XapianErlangDriver().
ResultEncoder XapianErlangDriver::m_result [private]
Definition at line 35 of file xapian_core.h.
Referenced by addDocument(), cancelTransaction(), commitTransaction(), createResource(), databaseInfo(), document(), enquire(), getDocumentById(), getLastDocId(), MSetQlcTable::getPage(), TermQlcTable::getPageKnownSize(), TermQlcTable::getPageUnknownSize(), getResourceInfo(), getResultEncoder(), MSetQlcTable::lookup(), TermQlcTable::lookup(), matchSet(), msetInfo(), open(), qlcInit(), qlcLookup(), qlcNext(), query(), releaseResource(), replaceDocument(), retrieveDocument(), retrieveTerm(), setDefaultPrefixes(), setDefaultStemmer(), startTransaction(), testResultEncoder(), and updateDocument().
ObjectRegister<const Xapian::Stem> XapianErlangDriver::m_stem_store [private]
Definition at line 46 of file xapian_core.h.
Referenced by XapianErlangDriver().
ResourceManager XapianErlangDriver::m_stores [private]
It is different for each port. It is a manager of ObjectRegisters.
Definition at line 62 of file xapian_core.h.
Referenced by createResource(), getRegisterByType(), open(), and XapianErlangDriver().
ObjectRegister<const Xapian::Weight> XapianErlangDriver::m_weight_store [private]
Definition at line 42 of file xapian_core.h.
Referenced by fillEnquire(), and XapianErlangDriver().
Xapian::Database* XapianErlangDriver::mp_db [private]
Definition at line 31 of file xapian_core.h.
Referenced by databaseInfo(), enquire(), getDocument(), getDocumentById(), getLastDocId(), matchSet(), open(), query(), XapianErlangDriver(), and ~XapianErlangDriver().
const Xapian::Stem* XapianErlangDriver::mp_default_stemmer [private]
Definition at line 33 of file xapian_core.h.
Referenced by applyDocument(), setDefaultStemmer(), XapianErlangDriver(), and ~XapianErlangDriver().
Xapian::WritableDatabase* XapianErlangDriver::mp_wdb [private]
Definition at line 32 of file xapian_core.h.
Referenced by addDocument(), assertWriteable(), cancelTransaction(), commitTransaction(), deleteDocument(), getDocument(), open(), replaceDocument(), setMetadata(), startTransaction(), updateDocument(), and XapianErlangDriver().
const uint8_t XapianErlangDriver::PARSER_FEATURE_COUNT = 13 [static]
Definition at line 262 of file xapian_core.h.
Referenced by idToParserFeature().
const unsigned XapianErlangDriver::PARSER_FEATURES [static]
Initial value:
 {
        0,
     Xapian::QueryParser::FLAG_BOOLEAN,
     Xapian::QueryParser::FLAG_PHRASE,
     Xapian::QueryParser::FLAG_LOVEHATE,
     Xapian::QueryParser::FLAG_BOOLEAN_ANY_CASE,
     Xapian::QueryParser::FLAG_WILDCARD,
     Xapian::QueryParser::FLAG_PURE_NOT,
     Xapian::QueryParser::FLAG_PARTIAL,
     Xapian::QueryParser::FLAG_SPELLING_CORRECTION,
     Xapian::QueryParser::FLAG_SYNONYM,
     Xapian::QueryParser::FLAG_AUTO_SYNONYMS,
     Xapian::QueryParser::FLAG_AUTO_MULTIWORD_SYNONYMS,
     Xapian::QueryParser::FLAG_DEFAULT
}
Definition at line 259 of file xapian_core.h.
Referenced by idToParserFeature().
const Xapian::QueryParser::stem_strategy XapianErlangDriver::STEM_STRATEGIES [static]
Initial value:
 {
     Xapian::QueryParser::STEM_NONE,
     Xapian::QueryParser::STEM_SOME,
     Xapian::QueryParser::STEM_ALL
}
Definition at line 268 of file xapian_core.h.
Referenced by readStemmingStrategy().
const uint8_t XapianErlangDriver::STEM_STRATEGY_COUNT = 3 [static]
Definition at line 265 of file xapian_core.h.
Referenced by readStemmingStrategy().
The documentation for this class was generated from the following files:
c_src/xapian_core.h
c_src/xapian_core.cpp