Xapian Erlang Binding: UserResource Class Reference
UserResource Class Reference
#include <user_resources.h>
Public Member Functions
UserResource (ResourceValidObjectType type, const std::string &name, CreateUserResourceFn creator)
ResourceObjectP create (ResourceManager &manager, ParamDecoder &params)
const std::string & getName ()
uint8_t getType ()
Private Attributes
ResourceValidObjectType m_type
std::string m_name
CreateUserResourceFn m_creator
Detailed Description
Encapsulate information about how to create new resource.
Definition at line 75 of file user_resources.h.
Constructor & Destructor Documentation
UserResource::UserResource (ResourceValidObjectType type, const std::string & name, CreateUserResourceFn creator) inline
Definition at line 82 of file user_resources.h.
Member Function Documentation
ResourceObjectP UserResource::create (ResourceManager & manager, ParamDecoder & params) inline
Definition at line 90 of file user_resources.h.
References m_creator.
Referenced by ResourceGenerator::create().
const std::string& UserResource::getName () inline
Definition at line 95 of file user_resources.h.
References m_name.
Referenced by Driver::getResourceInfo().
uint8_t UserResource::getType () inline
Definition at line 100 of file user_resources.h.
References m_type.
Referenced by Driver::getResourceInfo().
Member Data Documentation
CreateUserResourceFn UserResource::m_creator private
Definition at line 79 of file user_resources.h.
Referenced by create().
std::string UserResource::m_name private
Definition at line 78 of file user_resources.h.
Referenced by getName().
ResourceValidObjectType UserResource::m_type private
Definition at line 77 of file user_resources.h.
Referenced by getType().
The documentation for this class was generated from the following file:
c_src/user_resources.h