Xapian Erlang Binding: SpyController Class Reference
SpyController Class Reference
Controller of Xapian::MatchSet.
#include <spy_ctrl.h>
Public Member Functions
SpyController (Xapian::MatchSpy *spy)
SpyController (const SpyController &src)
Copy is allowed.
SpyController (SpyControllerInternal *src)
virtual ~SpyController ()
Xapian::MatchSpy * getSpy ()
virtual TermIteratorGenerator * getIteratorGenerator (ParamDecoder &param)
void finalize ()
bool is_finalized ()
Private Member Functions
void decref ()
Private Attributes
SpyControllerInternal * mp_internal
Detailed Description
Controller of Xapian::MatchSet.
This class do a lot of stuff. User can extend it for working other variants of MatchSpy.
getIteratorGenerator allows to create an object of type TermIteratorGenerator, which can be used inside TermQlcTable.
If the MatchSet cannot be used as TermGenerator, do not overwrite these methods. If the Erlang user will try to use this MatchSpy as a term iterator, an exception will be thrown.
MatchSpy can filled only once, after that it will be finalize.
Objects of this type are reference-counted. MatchSpy will be deleted in the destructor.
Definition at line 38 of file spy_ctrl.h.
Constructor & Destructor Documentation
SpyController::SpyController (Xapian::MatchSpy * spy)
Definition at line 57 of file spy_ctrl.cpp.
References mp_internal.
SpyController::SpyController (const SpyController & src)
Copy is allowed.
Definition at line 63 of file spy_ctrl.cpp.
References SpyControllerInternal::_refs, and mp_internal.
SpyController::SpyController (SpyControllerInternal * src)
Definition at line 70 of file spy_ctrl.cpp.
References SpyControllerInternal::_refs, and mp_internal.
SpyController::~SpyController () virtual
Definition at line 77 of file spy_ctrl.cpp.
References decref().
Member Function Documentation
void SpyController::decref () private
Definition at line 50 of file spy_ctrl.cpp.
References SpyControllerInternal::_refs, and mp_internal.
Referenced by ~SpyController().
void SpyController::finalize ()
Call it after using with add_matchspy.
Definition at line 97 of file spy_ctrl.cpp.
References SpyControllerInternal::finalize(), and mp_internal.
Referenced by Driver::matchSet().
TermIteratorGenerator * SpyController::getIteratorGenerator (ParamDecoder & param) virtual
Create an object. This method can be redifined by an user. It is reference-counted. Throw badarg error, if you can not use this MatchSet.
Reimplemented in ValueCountSpyController.
Definition at line 91 of file spy_ctrl.cpp.
Referenced by Driver::termGenerator().
Xapian::MatchSpy * SpyController::getSpy ()
Definition at line 84 of file spy_ctrl.cpp.
References SpyControllerInternal::getSpy(), and mp_internal.
Referenced by Driver::matchSet(), and SpyValueIteratorGenerator::SpyValueIteratorGenerator().
bool SpyController::is_finalized ()
Definition at line 102 of file spy_ctrl.cpp.
References SpyControllerInternal::is_finalized(), and mp_internal.
Referenced by Driver::matchSet().
Member Data Documentation
SpyControllerInternal* SpyController::mp_internal private
Definition at line 40 of file spy_ctrl.h.
Referenced by decref(), finalize(), getSpy(), is_finalized(), and SpyController().
The documentation for this class was generated from the following files:
c_src/spy_ctrl.h
c_src/spy_ctrl.cpp