Xapian Erlang Binding: TermIteratorGenerator Class Reference
TermIteratorGenerator Class Reference
Contains functions for iterator creation and retrieving information.
#include <termiter_gen.h>
Public Member Functions
virtual Xapian::TermIterator begin ()=0
virtual Xapian::TermIterator end ()=0
virtual ~TermIteratorGenerator ()
virtual Xapian::termcount size ()
virtual bool empty ()
Detailed Description
Contains functions for iterator creation and retrieving information.
It provides an interface for term iteration. Each object contains state with a term set.
Used from Driver::termGenerator for QLC iterators.
Definition at line 17 of file termiter_gen.h.
Constructor & Destructor Documentation
virtual TermIteratorGenerator::~TermIteratorGenerator () inline virtual
Definition at line 22 of file termiter_gen.h.
Member Function Documentation
virtual Xapian::TermIterator TermIteratorGenerator::begin () pure virtual
Implemented in TopSpyValueIteratorGenerator, SpyValueIteratorGenerator, and DocumentTermIteratorGenerator.
Referenced by empty(), TermQlcTable::goTo(), TermQlcTable::lookup(), and TermQlcTable::TermQlcTable().
virtual bool TermIteratorGenerator::empty () inline virtual
Definition at line 32 of file termiter_gen.h.
References begin(), and end().
Referenced by TermQlcTable::TermQlcTable().
virtual Xapian::TermIterator TermIteratorGenerator::end () pure virtual
Implemented in TopSpyValueIteratorGenerator, SpyValueIteratorGenerator, and DocumentTermIteratorGenerator.
Referenced by empty(), and TermQlcTable::TermQlcTable().
virtual Xapian::termcount TermIteratorGenerator::size () inline virtual
If size() is unknown, return 0. To check size is really 0, use empty().
Reimplemented in DocumentTermIteratorGenerator.
Definition at line 28 of file termiter_gen.h.
Referenced by TermQlcTable::TermQlcTable().
The documentation for this class was generated from the following file:
c_src/termiter_gen.h