Xapian Erlang Binding: ObjectRegister< Child > Class Template Reference
ObjectRegister< Child > Class Template Reference
#include <object_register.h>
Public Types
typedef google::dense_hash_map
< uint32_t, Child *, HASH_TPL
< uint32_t > > Hash
Public Member Functions
ObjectRegister ()
Child * get (Counter num)
Counter put (Child *obj)
void * getVoidPointer (Counter num)
Counter putVoidPointer (void *obj)
void remove (Counter num)
void * replaceWithoutCleaning (uint32_t num, void *new_obj)
Hash & getElements ()
~ObjectRegister ()
Public Member Functions inherited from ObjectBaseRegister
virtual ~ObjectBaseRegister ()
Private Attributes
Counter m_counter
Hash m_elements
Additional Inherited Members
Protected Types inherited from ObjectBaseRegister
typedef uint32_t Counter
Detailed Description
template<class Child>
class ObjectRegister< Child >
Definition at line 39 of file object_register.h.
Member Typedef Documentation
template<class Child> typedef google::dense_hash_map< uint32_t, Child*, HASH_TPL<uint32_t> > ObjectRegister< Child >::Hash
Definition at line 43 of file object_register.h.
Constructor & Destructor Documentation
template<class Child > XAPIAN_ERLANG_NS_BEGIN ObjectRegister< Child >::ObjectRegister ()
Definition at line 13 of file object_register.hpp.
template<class Child > ObjectRegister< Child >::~ObjectRegister ()
Definition at line 76 of file object_register.hpp.
Member Function Documentation
template<class Child > Child * ObjectRegister< Child >::get (Counter num)
Definition at line 48 of file object_register.hpp.
Referenced by ResourceGenerator::add(), ResourceGenerator::create(), Driver::fillEnquire(), Driver::matchSet(), Driver::msetInfo(), Driver::qlcInit(), Driver::qlcLookup(), Driver::qlcNext(), and Driver::termGenerator().
template<class Child> Hash& ObjectRegister< Child >::getElements () inline
Definition at line 73 of file object_register.h.
Referenced by Driver::getResourceInfo().
template<class Child > void * ObjectRegister< Child >::getVoidPointer (Counter num) virtual
Implements ObjectBaseRegister.
Definition at line 62 of file object_register.hpp.
template<class Child> ObjectRegister< Child >::Counter ObjectRegister< Child >::put (Child * obj)
Definition at line 22 of file object_register.hpp.
Referenced by ResourceGenerator::add(), Driver::document(), Driver::enquire(), Driver::matchSet(), and Driver::qlcInit().
template<class Child > ObjectRegister< Child >::Counter ObjectRegister< Child >::putVoidPointer (void * obj) virtual
Implements ObjectBaseRegister.
Definition at line 70 of file object_register.hpp.
template<class Child > void ObjectRegister< Child >::remove (Counter num) virtual
Implements ObjectBaseRegister.
Definition at line 33 of file object_register.hpp.
template<class Child > void * ObjectRegister< Child >::replaceWithoutCleaning (uint32_t num, void * new_obj) virtual
Implements ObjectBaseRegister.
Definition at line 89 of file object_register.hpp.
Member Data Documentation
template<class Child> Counter ObjectRegister< Child >::m_counter private
Definition at line 47 of file object_register.h.
template<class Child> Hash ObjectRegister< Child >::m_elements private
Definition at line 48 of file object_register.h.
Referenced by ObjectRegister< Xapian::Document >::getElements().
The documentation for this class was generated from the following files:
c_src/object_register.h
c_src/object_register.hpp