Xapian Erlang Binding: c_src/common/resource/cons.cpp File Reference
cons.cpp File Reference
#include "resource/constructor.h"
#include "resource/generator.h"
#include "resource/element.h"
#include "resource/register.h"
#include "param_decoder.h"
#include "xapian.h"
#include "xapian_config.h"
Functions
Element createBoolWeight (Register &, ParamDecoder &)
Element createBM25Weight (Register &, ParamDecoder &params)
Element createTradWeight (Register &, ParamDecoder &params)
Element createValueCountMatchSpy (Register &, ParamDecoder &params)
Element createMultiValueKeyMaker (Register &, ParamDecoder &params)
Element createDateValueRangeProcessor3 (Register &, ParamDecoder &params)
Element createDateValueRangeProcessor5 (Register &, ParamDecoder &params)
Element createNumberValueRangeProcessor1 (Register &, ParamDecoder &params)
Element createNumberValueRangeProcessor3 (Register &, ParamDecoder &params)
Element createStringValueRangeProcessor1 (Register &, ParamDecoder &params)
Element createStringValueRangeProcessor3 (Register &, ParamDecoder &params)
Element createSimpleStopper (Register &, ParamDecoder &params)
Function Documentation
Element createBM25Weight (Register & , ParamDecoder & params)
Definition at line 25 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createBoolWeight (Register & , ParamDecoder &)
Definition at line 18 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createDateValueRangeProcessor3 (Register & , ParamDecoder & params)
Definition at line 68 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createDateValueRangeProcessor5 (Register & , ParamDecoder & params)
Definition at line 79 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createMultiValueKeyMaker (Register & , ParamDecoder & params)
Definition at line 53 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createNumberValueRangeProcessor1 (Register & , ParamDecoder & params)
Definition at line 93 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createNumberValueRangeProcessor3 (Register & , ParamDecoder & params)
Definition at line 102 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createSimpleStopper (Register & , ParamDecoder & params)
Definition at line 133 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createStringValueRangeProcessor1 (Register & , ParamDecoder & params)
Definition at line 113 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createStringValueRangeProcessor3 (Register & , ParamDecoder & params)
Definition at line 122 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createTradWeight (Register & , ParamDecoder & params)
Definition at line 37 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().
Element createValueCountMatchSpy (Register & , ParamDecoder & params)
Definition at line 45 of file cons.cpp.
References Element::wrap().
Referenced by Generator::registerCallbacks().