Xapian Erlang Binding: c_src/user_resources.h File Reference
user_resources.h File Reference
#include "object_register.h"
#include "param_decoder.h"
#include <stdint.h>
#include "xapian_exception.h"
#include "xapian_config.h"
#include <iostream>
Classes
class ResourceType
class UserResource
class ResourceGenerator
class ResourceManager
Namespaces
namespace Xapian
Typedefs
typedef uint8_t ResourceObjectType
typedef uint32_t ResourceObjectNum
typedef
ResourceType::ResourceValidObjectType ResourceValidObjectType
typedef ResourceObjectP(* CreateUserResourceFn)(ResourceManager &manager, ParamDecoder &params)
Functions
void registerUserCallbacks (ResourceGenerator &generator)
Variables
XAPIAN_ERLANG_NS_BEGIN typedef
void * ResourceObjectP
Typedef Documentation
typedef ResourceObjectP(* CreateUserResourceFn)(ResourceManager &manager, ParamDecoder &params)
CreateUserResourceFn is a function for calling new Constructor of a resource.
Definition at line 68 of file user_resources.h.
typedef uint32_t ResourceObjectNum
Definition at line 20 of file user_resources.h.
typedef uint8_t ResourceObjectType
Definition at line 19 of file user_resources.h.
typedef ResourceType::ResourceValidObjectType ResourceValidObjectType
It is a number for each class, which can be handled as a resource.
Definition at line 62 of file user_resources.h.
Function Documentation
void registerUserCallbacks (ResourceGenerator & generator)
Definition at line 51 of file user_resources.cpp.
References ResourceGenerator::add(), createBM25Weight(), createBoolWeight(), createTradWeight(), createValueCountMatchSpy(), ResourceType::MATCH_SPY, and ResourceType::WEIGHT.
Referenced by Driver::init().
Variable Documentation
XAPIAN_ERLANG_NS_BEGIN typedef void* ResourceObjectP
Definition at line 18 of file user_resources.h.
Referenced by ResourceManager::createAndRegister().