Xapian Erlang Binding: c_src/port/xapian_port.cpp File Reference
xapian_port.cpp File Reference
#include <iostream>
#include <stdint.h>
#include <assert.h>
#include "xapian_core.h"
#include "memory_manager.h"
#include "param_decoder.h"
#include "result_encoder.h"
Functions
XAPIAN_ERLANG_NS_BEGIN int is_big_endian ()
uint32_t swapByteOrder (uint32_t ui)
uint32_t read_packet_length (std::istream &s)
std::ostream & write_packet_length (std::ostream &s, uint32_t len)
void run ()
XAPIAN_ERLANG_NS_END int main (void)
Function Documentation
XAPIAN_ERLANG_NS_BEGIN int is_big_endian ()
Definition at line 23 of file xapian_port.cpp.
Referenced by read_packet_length(), and write_packet_length().
XAPIAN_ERLANG_NS_END int main (void)
Definition at line 122 of file xapian_port.cpp.
References run().
uint32_t read_packet_length (std::istream & s)
Definition at line 46 of file xapian_port.cpp.
References is_big_endian(), and swapByteOrder().
Referenced by run().
void run ()
Create global variables
Definition at line 68 of file xapian_port.cpp.
References ResultEncoder::clear(), ResultEncoder::finalize(), ResultEncoder::finalSize(), Driver::handleCommand(), ResultEncoder::isExtended(), read_packet_length(), ResultEncoder::setBuffer(), and write_packet_length().
Referenced by main().
uint32_t swapByteOrder (uint32_t ui)
Reverse bytes in the unsigned integer.
Definition at line 37 of file xapian_port.cpp.
Referenced by read_packet_length(), and write_packet_length().
std::ostream& write_packet_length (std::ostream & s, uint32_t len)
Definition at line 55 of file xapian_port.cpp.
References is_big_endian(), and swapByteOrder().
Referenced by run().